// Generated by BoneScript compiler. DO NOT EDIT.
// Service: ItemService
import { Router, Request, Response } from "express";
import { v4 as uuid } from "uuid";
import { query, queryOne, execute, pool } from "../db";
import { eventBus } from "../events";
import { requireAuth, AuthContext } from "../auth";
import { logger } from "../logger";
import { counter } from "../metrics";
import * as __algorithms from "../algorithms";
const { shortestPath, topologicalSort, binarySearch, bipartiteMatching, roundRobin, weightedAverage, percentile, rankBy, consistentHash } = __algorithms as any;

import { transitionItem, ITEM_INITIAL } from "../state_machines/item";

export const itemsRouter = Router();

// CREATE
itemsRouter.post("/", requireAuth, async (req: Request, res: Response) => {
  try {
    const id = uuid();
    const { name, quantity, rarity, tradeable, owner_id, metadata } = req.body;
    const state = ITEM_INITIAL;
    const sql = `INSERT INTO items (id, name, quantity, rarity, tradeable, owner_id, metadata, state) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING *`;
    const rows = await query(sql, [id, name, quantity, rarity, tradeable, owner_id, metadata, state]);
    counter("entity.created", { entity: "Item" });
    res.status(201).json(rows[0]);
  } catch (e: any) {
    res.status(400).json({ error: { code: "CREATE_FAILED", message: e.message } });
  }
});

// READ
itemsRouter.get("/:id", requireAuth, async (req: Request, res: Response) => {
  const row = await queryOne(`SELECT * FROM items WHERE id = $1`, [req.params.id]);
  if (!row) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(row);
});

// LIST
itemsRouter.get("/", requireAuth, async (req: Request, res: Response) => {
  const page = parseInt(req.query.page as string) || 1;
  const pageSize = Math.min(parseInt(req.query.page_size as string) || 50, 100);
  const offset = (page - 1) * pageSize;
  const rows = await query(`SELECT * FROM items ORDER BY created_at DESC LIMIT $1 OFFSET $2`, [pageSize, offset]);
  const [{ count }] = await query(`SELECT COUNT(*) as count FROM items`);
  res.json({ items: rows, total: parseInt(count), page, page_size: pageSize });
});

// UPDATE
itemsRouter.put("/:id", requireAuth, async (req: Request, res: Response) => {
  const fields = { ...req.body };
  // State machine enforcement
  if (fields.state !== undefined) {
    const current = await queryOne<{ state: string }>(`SELECT state FROM items WHERE id = $1`, [req.params.id]);
    if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    const tr = transitionItem(current.state as any, fields.state);
    if (!tr.ok) return res.status(422).json({ error: { code: "INVALID_TRANSITION", message: tr.error } });
  }
  const sets = Object.keys(fields).map((k, i) => `${k} = $${i + 2}`).join(", ");
  const values = Object.values(fields);
  const sql = `UPDATE items SET ${sets}, updated_at = NOW() WHERE id = $1 RETURNING *`;
  const rows = await query(sql, [req.params.id, ...values]);
  if (rows.length === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(rows[0]);
});

// DELETE
itemsRouter.delete("/:id", requireAuth, async (req: Request, res: Response) => {
  const count = await execute(`DELETE FROM items WHERE id = $1`, [req.params.id]);
  if (count === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.status(204).send();
});

// CAPABILITY: consume_item [transactional]
itemsRouter.post("/consume-item", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const player = await queryOne(`SELECT * FROM players WHERE id = $1`, [req.body.player_id || req.params.id]);
    if (!player) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "player not found" } });
    }
    const item = await queryOne(`SELECT * FROM items WHERE id = $1`, [req.body.item_id || req.params.id]);
    if (!item) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "item not found" } });
    }

    // Preconditions
    if (!(player?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "player.state == \"active\"" } });
    }
    if (!(item?.owner_id === player?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "item.owner_id == player.id" } });
    }
    if (!(item?.state === "available")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "item.state == \"available\"" } });
    }
    if (!(item?.quantity > 0)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "item.quantity > 0" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE items SET quantity = quantity - $1, updated_at = NOW() WHERE id = $2 RETURNING *`, [1, req.body.item_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: item.quantity -= 1");
    }

    res.json({ ok: true, action: "consume_item", entity: player });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});
