// Generated by BoneScript compiler. DO NOT EDIT.
// Service: PlayerService
import { Router, Request, Response } from "express";
import { v4 as uuid } from "uuid";
import { query, queryOne, execute, pool } from "../db";
import { eventBus } from "../events";
import { requireAuth, AuthContext } from "../auth";
import { logger } from "../logger";
import { counter } from "../metrics";
import * as __algorithms from "../algorithms";
const { shortestPath, topologicalSort, binarySearch, bipartiteMatching, roundRobin, weightedAverage, percentile, rankBy, consistentHash } = __algorithms as any;

// User-defined functions referenced in effects — implement these or use extension_point
declare function calculate_level(...args: any[]): any;

import { transitionPlayer, PLAYER_INITIAL } from "../state_machines/player";

export const playersRouter = Router();

// CREATE
playersRouter.post("/", requireAuth, async (req: Request, res: Response) => {
  try {
    const id = uuid();
    const { username, email, score, level, inventory } = req.body;
    const state = PLAYER_INITIAL;
    const sql = `INSERT INTO players (id, username, email, score, level, inventory, state) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *`;
    const rows = await query(sql, [id, username, email, score, level, inventory, state]);
    counter("entity.created", { entity: "Player" });
    res.status(201).json(rows[0]);
  } catch (e: any) {
    res.status(400).json({ error: { code: "CREATE_FAILED", message: e.message } });
  }
});

// READ
playersRouter.get("/:id", requireAuth, async (req: Request, res: Response) => {
  const row = await queryOne(`SELECT * FROM players WHERE id = $1`, [req.params.id]);
  if (!row) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(row);
});

// LIST
playersRouter.get("/", requireAuth, async (req: Request, res: Response) => {
  const page = parseInt(req.query.page as string) || 1;
  const pageSize = Math.min(parseInt(req.query.page_size as string) || 50, 100);
  const offset = (page - 1) * pageSize;
  const rows = await query(`SELECT * FROM players ORDER BY created_at DESC LIMIT $1 OFFSET $2`, [pageSize, offset]);
  const [{ count }] = await query(`SELECT COUNT(*) as count FROM players`);
  res.json({ items: rows, total: parseInt(count), page, page_size: pageSize });
});

// UPDATE
playersRouter.put("/:id", requireAuth, async (req: Request, res: Response) => {
  const fields = { ...req.body };
  // State machine enforcement
  if (fields.state !== undefined) {
    const current = await queryOne<{ state: string }>(`SELECT state FROM players WHERE id = $1`, [req.params.id]);
    if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    const tr = transitionPlayer(current.state as any, fields.state);
    if (!tr.ok) return res.status(422).json({ error: { code: "INVALID_TRANSITION", message: tr.error } });
  }
  const sets = Object.keys(fields).map((k, i) => `${k} = $${i + 2}`).join(", ");
  const values = Object.values(fields);
  const sql = `UPDATE players SET ${sets}, updated_at = NOW() WHERE id = $1 RETURNING *`;
  const rows = await query(sql, [req.params.id, ...values]);
  if (rows.length === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(rows[0]);
});

// DELETE
playersRouter.delete("/:id", requireAuth, async (req: Request, res: Response) => {
  const count = await execute(`DELETE FROM players WHERE id = $1`, [req.params.id]);
  if (count === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.status(204).send();
});

// CAPABILITY: create_trade [transactional]
playersRouter.post("/create-trade", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    const { items } = req.body;

    // Fetch entities
    const from = await queryOne(`SELECT * FROM players WHERE id = $1`, [req.body.from_id || req.params.id]);
    if (!from) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "from not found" } });
    }
    const to = await queryOne(`SELECT * FROM players WHERE id = $1`, [req.body.to_id || req.params.id]);
    if (!to) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "to not found" } });
    }

    // Preconditions
    if (!(from?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "from.state == \"active\"" } });
    }
    if (!(to?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "to.state == \"active\"" } });
    }
    if (!(from !== to)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "from != to" } });
    }
    if (!(items?.size >= 1)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "items.size >= 1" } });
    }
    if (!(items?.size <= 10)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "items.size <= 10" } });
    }

    // Effects (applied in declaration order)
    // EFFECT: items.state = "reserved"
    // TODO: Implement this effect manually

    // Emit events
    await eventBus.publish("TradeOfferCreated", { from_id: from?.id, to_id: to?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "PlayerService", auth.trace_id, __client);

    res.json({ ok: true, action: "create_trade", entity: from });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});

// CAPABILITY: accept_trade [transactional]
playersRouter.post("/accept-trade", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const trade = await queryOne(`SELECT * FROM trade_offers WHERE id = $1`, [req.body.trade_id || req.params.id]);
    if (!trade) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "trade not found" } });
    }
    const acceptor = await queryOne(`SELECT * FROM players WHERE id = $1`, [req.body.acceptor_id || req.params.id]);
    if (!acceptor) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "acceptor not found" } });
    }

    // Preconditions
    if (!(trade?.status === "pending")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "trade.status == \"pending\"" } });
    }
    if (!(trade?.to_player === acceptor?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "trade.to_player == acceptor.id" } });
    }
    if (!(acceptor?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "acceptor.state == \"active\"" } });
    }
    if (!(trade?.expires_at > new Date())) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "trade.expires_at > now()" } });
    }

    // Effects (applied in declaration order)
    // EFFECT: trade.status = "accepted"
    // TODO: Implement this effect manually
    // EFFECT: trade.offered_items.owner_id = trade.to_player
    // TODO: Implement this effect manually
    // EFFECT: trade.requested_items.owner_id = trade.from_player
    // TODO: Implement this effect manually

    // Emit events
    await eventBus.publish("ItemTraded", { trade_id: trade?.id, acceptor_id: acceptor?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "PlayerService", auth.trace_id, __client);

    res.json({ ok: true, action: "accept_trade", entity: trade });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});

// CAPABILITY: award_xp
playersRouter.post("/award-xp", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  try {
    // sync: eventual — effects applied, events queued via outbox
    const { amount } = req.body;

    // Fetch entities
    const player = await queryOne(`SELECT * FROM players WHERE id = $1`, [req.body.player_id || req.params.id]);
    if (!player) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "player not found" } });
    }

    // Preconditions
    if (!(player?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "player.state == \"active\"" } });
    }
    if (!(amount > 0)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "amount > 0" } });
    }
    if (!(amount <= 10000)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "amount <= 10000" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE players SET score = score + $1, updated_at = NOW() WHERE id = $2 RETURNING *`, [amount, req.body.player_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: player.score += amount");
    }
    const __effect_1 = await query(`UPDATE players SET level = $1, updated_at = NOW() WHERE id = $2 RETURNING *`, [calculate_level(player?.score + amount), req.body.player_id || req.params.id]);
    if (!__effect_1 || __effect_1.length === 0) {
      throw new Error("Effect failed: player.level = calculate_level((player.score + amount))");
    }

    // Emit events
    await eventBus.publish("PlayerLeveledUp", { player_id: player?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "PlayerService", auth.trace_id);

    res.json({ ok: true, action: "award_xp", entity: player });
  } catch (e: any) {
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  }
});

// CAPABILITY: consume_item [transactional]
playersRouter.post("/consume-item", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const player = await queryOne(`SELECT * FROM players WHERE id = $1`, [req.body.player_id || req.params.id]);
    if (!player) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "player not found" } });
    }
    const item = await queryOne(`SELECT * FROM items WHERE id = $1`, [req.body.item_id || req.params.id]);
    if (!item) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "item not found" } });
    }

    // Preconditions
    if (!(player?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "player.state == \"active\"" } });
    }
    if (!(item?.owner_id === player?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "item.owner_id == player.id" } });
    }
    if (!(item?.state === "available")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "item.state == \"available\"" } });
    }
    if (!(item?.quantity > 0)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "item.quantity > 0" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE items SET quantity = quantity - $1, updated_at = NOW() WHERE id = $2 RETURNING *`, [1, req.body.item_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: item.quantity -= 1");
    }

    res.json({ ok: true, action: "consume_item", entity: player });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});
