// Generated by BoneScript compiler. DO NOT EDIT.
// Service: TradeOfferService
import { Router, Request, Response } from "express";
import { v4 as uuid } from "uuid";
import { query, queryOne, execute, pool } from "../db";
import { eventBus } from "../events";
import { requireAuth, AuthContext } from "../auth";
import { logger } from "../logger";
import { counter } from "../metrics";
import * as __algorithms from "../algorithms";
const { shortestPath, topologicalSort, binarySearch, bipartiteMatching, roundRobin, weightedAverage, percentile, rankBy, consistentHash } = __algorithms as any;

import { transitionTradeOffer, TRADEOFFER_INITIAL } from "../state_machines/trade_offer";

export const tradeOffersRouter = Router();

// CREATE
tradeOffersRouter.post("/", requireAuth, async (req: Request, res: Response) => {
  try {
    const id = uuid();
    const { from_player, to_player, offered_items, requested_items, status, expires_at } = req.body;
    const state = TRADEOFFER_INITIAL;
    const sql = `INSERT INTO trade_offers (id, from_player, to_player, offered_items, requested_items, status, expires_at, state) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING *`;
    const rows = await query(sql, [id, from_player, to_player, offered_items, requested_items, status, expires_at, state]);
    counter("entity.created", { entity: "TradeOffer" });
    res.status(201).json(rows[0]);
  } catch (e: any) {
    res.status(400).json({ error: { code: "CREATE_FAILED", message: e.message } });
  }
});

// READ
tradeOffersRouter.get("/:id", requireAuth, async (req: Request, res: Response) => {
  const row = await queryOne(`SELECT * FROM trade_offers WHERE id = $1`, [req.params.id]);
  if (!row) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(row);
});

// LIST
tradeOffersRouter.get("/", requireAuth, async (req: Request, res: Response) => {
  const page = parseInt(req.query.page as string) || 1;
  const pageSize = Math.min(parseInt(req.query.page_size as string) || 50, 100);
  const offset = (page - 1) * pageSize;
  const rows = await query(`SELECT * FROM trade_offers ORDER BY created_at DESC LIMIT $1 OFFSET $2`, [pageSize, offset]);
  const [{ count }] = await query(`SELECT COUNT(*) as count FROM trade_offers`);
  res.json({ items: rows, total: parseInt(count), page, page_size: pageSize });
});

// UPDATE
tradeOffersRouter.put("/:id", requireAuth, async (req: Request, res: Response) => {
  const fields = { ...req.body };
  // State machine enforcement
  if (fields.state !== undefined) {
    const current = await queryOne<{ state: string }>(`SELECT state FROM trade_offers WHERE id = $1`, [req.params.id]);
    if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    const tr = transitionTradeOffer(current.state as any, fields.state);
    if (!tr.ok) return res.status(422).json({ error: { code: "INVALID_TRANSITION", message: tr.error } });
  }
  const sets = Object.keys(fields).map((k, i) => `${k} = $${i + 2}`).join(", ");
  const values = Object.values(fields);
  const sql = `UPDATE trade_offers SET ${sets}, updated_at = NOW() WHERE id = $1 RETURNING *`;
  const rows = await query(sql, [req.params.id, ...values]);
  if (rows.length === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(rows[0]);
});

// DELETE
tradeOffersRouter.delete("/:id", requireAuth, async (req: Request, res: Response) => {
  const count = await execute(`DELETE FROM trade_offers WHERE id = $1`, [req.params.id]);
  if (count === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.status(204).send();
});

// CAPABILITY: accept_trade [transactional]
tradeOffersRouter.post("/accept-trade", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const trade = await queryOne(`SELECT * FROM trade_offers WHERE id = $1`, [req.body.trade_id || req.params.id]);
    if (!trade) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "trade not found" } });
    }
    const acceptor = await queryOne(`SELECT * FROM players WHERE id = $1`, [req.body.acceptor_id || req.params.id]);
    if (!acceptor) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "acceptor not found" } });
    }

    // Preconditions
    if (!(trade?.status === "pending")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "trade.status == \"pending\"" } });
    }
    if (!(trade?.to_player === acceptor?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "trade.to_player == acceptor.id" } });
    }
    if (!(acceptor?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "acceptor.state == \"active\"" } });
    }
    if (!(trade?.expires_at > new Date())) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "trade.expires_at > now()" } });
    }

    // Effects (applied in declaration order)
    // EFFECT: trade.status = "accepted"
    // TODO: Implement this effect manually
    // EFFECT: trade.offered_items.owner_id = trade.to_player
    // TODO: Implement this effect manually
    // EFFECT: trade.requested_items.owner_id = trade.from_player
    // TODO: Implement this effect manually

    // Emit events
    await eventBus.publish("ItemTraded", { trade_id: trade?.id, acceptor_id: acceptor?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "TradeOfferService", auth.trace_id, __client);

    res.json({ ok: true, action: "accept_trade", entity: trade });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});
