// Generated by BoneScript compiler. DO NOT EDIT.
import { Request, Response, NextFunction } from "express";
import jwt from "jsonwebtoken";

const JWT_SECRET = process.env.JWT_SECRET || "bonescript-dev-secret-change-in-production";

export interface AuthContext {
  authenticated: boolean;
  actor_id: string | null;
  trace_id: string;
}

export function authMiddleware(req: Request, res: Response, next: NextFunction): void {
  const header = req.headers.authorization;
  if (!header || !header.startsWith("Bearer ")) {
    (req as any).auth = { authenticated: false, actor_id: null, trace_id: req.headers["x-trace-id"] || "" };
    next();
    return;
  }
  try {
    const token = header.slice(7);
    const decoded = jwt.verify(token, JWT_SECRET) as { sub: string };
    (req as any).auth = {
      authenticated: true,
      actor_id: decoded.sub,
      trace_id: req.headers["x-trace-id"] || "",
    };
  } catch {
    (req as any).auth = { authenticated: false, actor_id: null, trace_id: req.headers["x-trace-id"] || "" };
  }
  next();
}

export function requireAuth(req: Request, res: Response, next: NextFunction): void {
  const auth: AuthContext = (req as any).auth;
  if (!auth || !auth.authenticated) {
    res.status(401).json({ error: { code: "UNAUTHORIZED", message: "Authentication required" } });
    return;
  }
  next();
}
