// Generated by BoneScript compiler. DO NOT EDIT.
// Implements spec/10 Â§5 (Health Checks)

import { Router, Request, Response } from "express";
import { pool } from "./db";
import { dump as dumpMetrics } from "./metrics";

export const healthRouter = Router();

// Liveness â€” is the process running?
healthRouter.get("/live", (_req: Request, res: Response) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

// Readiness â€” can the service accept requests?
healthRouter.get("/ready", async (_req: Request, res: Response) => {
  const checks: Record<string, { ok: boolean; message?: string }> = {};

  // Postgres
  try {
    await pool.query("SELECT 1");
    checks.postgres = { ok: true };
  } catch (e: any) {
    checks.postgres = { ok: false, message: e.message };
  }

  const allOk = Object.values(checks).every(c => c.ok);
  res.status(allOk ? 200 : 503).json({
    status: allOk ? "ok" : "degraded",
    checks,
    timestamp: new Date().toISOString(),
  });
});

// Startup â€” has initialization completed?
healthRouter.get("/startup", (_req: Request, res: Response) => {
  res.json({ status: "ok", uptime: process.uptime() });
});

// Prometheus-style metrics
healthRouter.get("/metrics", (_req: Request, res: Response) => {
  res.type("text/plain").send(dumpMetrics());
});
