// Generated by BoneScript compiler. DO NOT EDIT.
// System: InventoryPlatform
import express from "express";
import { createServer } from "http";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import { authMiddleware } from "./auth";
import { healthRouter } from "./health";
import { logger } from "./logger";
import { eventBus } from "./events";
import { pool } from "./db";
import { setupWebSocketServer } from "./websocket";

import { playersRouter } from "./routes/player";
import { itemsRouter } from "./routes/item";
import { tradeOffersRouter } from "./routes/trade_offer";

const app = express();
const httpServer = createServer(app);
const PORT = parseInt(process.env.PORT || "3000");

// Middleware
app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(authMiddleware);
app.use(rateLimit({ windowMs: 60000, max: 100 }));

// Request timeout (default 30s, override per-route)
app.use((req: any, res: any, next: any) => {
  const timeout = parseInt(process.env.REQUEST_TIMEOUT_MS || "30000");
  const timer = setTimeout(() => {
    if (!res.headersSent) {
      res.status(503).json({ error: { code: "REQUEST_TIMEOUT", message: "Request timed out" } });
    }
  }, timeout);
  res.on("finish", () => clearTimeout(timer));
  next();
});

// Health & metrics
app.use("/health", healthRouter);

// Routes
app.use("/players", playersRouter);
app.use("/items", itemsRouter);
app.use("/trade_offers", tradeOffersRouter);

// WebSocket
setupWebSocketServer(httpServer);

// Start
httpServer.listen(PORT, () => {
  logger.info("server_started", { event: "startup", metadata: { port: PORT } });
  // Start durable event worker (no-op in in_process mode)
  eventBus.startWorker(parseInt(process.env.EVENT_WORKER_INTERVAL_MS || "1000"));
  console.log(`[InventoryPlatform] Running on port ${PORT}`);
  console.log(`  HTTP routes:`);
  console.log(`    /players`);
  console.log(`    /items`);
  console.log(`    /trade_offers`);
  console.log(`  WebSocket: /ws?channel=<name>&token=<jwt>`);
  console.log(`  Health: /health/live, /health/ready, /health/metrics`);
});

// Graceful shutdown
const shutdown = async (signal: string) => {
  logger.info("server_stopping", { event: "shutdown", metadata: { signal } });
  httpServer.close(async () => {
    try {
      await pool.end();
      logger.info("server_stopped", { event: "shutdown", status: "success" });
    } catch (e: any) {
      logger.error("shutdown_error", { event: "shutdown", metadata: { error: e.message } });
    }
    process.exit(0);
  });
  // Force exit after 10s if connections don't drain
  setTimeout(() => { logger.error("shutdown_timeout", { event: "shutdown" }); process.exit(1); }, 10000);
};
process.on("SIGTERM", () => shutdown("SIGTERM"));
process.on("SIGINT", () => shutdown("SIGINT"));

export { app, httpServer };