// Generated by BoneScript compiler. DO NOT EDIT.
import { pool } from "./db";

async function migrate() {
  console.log("Running migrations...");
  const client = await pool.connect();
  try {
    await client.query(`-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: 85dbdc0221e5bebe
-- Module: PlayerStore

CREATE TABLE IF NOT EXISTS player_stores (
  id UUID NOT NULL PRIMARY KEY,
  username VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  password_hash VARCHAR NOT NULL,
  score BIGINT NOT NULL,
  level BIGINT NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);


CREATE OR REPLACE FUNCTION update_player_stores_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_player_stores_updated_at
  BEFORE UPDATE ON player_stores
  FOR EACH ROW
  EXECUTE FUNCTION update_player_stores_updated_at();
`);
    await client.query(`-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: 85dbdc0221e5bebe
-- Module: ItemStore

CREATE TABLE IF NOT EXISTS item_stores (
  id UUID NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  quantity BIGINT NOT NULL,
  rarity VARCHAR NOT NULL,
  tradeable BOOLEAN NOT NULL,
  owner_id UUID NOT NULL,
  state VARCHAR NOT NULL,
  metadata JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);


CREATE OR REPLACE FUNCTION update_item_stores_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_item_stores_updated_at
  BEFORE UPDATE ON item_stores
  FOR EACH ROW
  EXECUTE FUNCTION update_item_stores_updated_at();
`);
    await client.query(`-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: 85dbdc0221e5bebe
-- Module: PlayerStore

CREATE TABLE IF NOT EXISTS player_stores (
  id UUID NOT NULL PRIMARY KEY,
  username VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  password_hash VARCHAR NOT NULL,
  score BIGINT NOT NULL,
  level BIGINT NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);


CREATE OR REPLACE FUNCTION update_player_stores_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_player_stores_updated_at
  BEFORE UPDATE ON player_stores
  FOR EACH ROW
  EXECUTE FUNCTION update_player_stores_updated_at();
`);
    await client.query(`-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: 85dbdc0221e5bebe
-- Module: ItemStore

CREATE TABLE IF NOT EXISTS item_stores (
  id UUID NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  quantity BIGINT NOT NULL,
  rarity VARCHAR NOT NULL,
  tradeable BOOLEAN NOT NULL,
  owner_id UUID NOT NULL,
  state VARCHAR NOT NULL,
  metadata JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);


CREATE OR REPLACE FUNCTION update_item_stores_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_item_stores_updated_at
  BEFORE UPDATE ON item_stores
  FOR EACH ROW
  EXECUTE FUNCTION update_item_stores_updated_at();
`);
    await client.query(`-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: 85dbdc0221e5bebe
-- Module: TradeOfferService

CREATE TABLE IF NOT EXISTS trade_offers (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  from_player UUID NOT NULL,
  to_player UUID NOT NULL,
  offered_items JSONB NOT NULL,
  requested_items JSONB NOT NULL,
  status VARCHAR NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_trade_offers_from_player_to_player_status ON trade_offers (from_player, to_player, status);

CREATE OR REPLACE FUNCTION update_trade_offers_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_trade_offers_updated_at
  BEFORE UPDATE ON trade_offers
  FOR EACH ROW
  EXECUTE FUNCTION update_trade_offers_updated_at();
`);
    console.log("Migrations complete.");
  } finally {
    client.release();
    await pool.end();
  }
}

migrate().catch(e => { console.error(e); process.exit(1); });