// Generated by BoneScript compiler. DO NOT EDIT.
// Service: OrderService
import { Router, Request, Response } from "express";
import { v4 as uuid } from "uuid";
import { query, queryOne, execute, pool } from "../db";
import { eventBus } from "../events";
import { requireAuth, AuthContext } from "../auth";
import { logger } from "../logger";
import { counter } from "../metrics";
import * as __algorithms from "../algorithms";
const { shortestPath, topologicalSort, binarySearch, bipartiteMatching, roundRobin, weightedAverage, percentile, rankBy, consistentHash } = __algorithms as any;

import { transitionOrder, ORDER_INITIAL } from "../state_machines/order";

export const ordersRouter = Router();

// CREATE
ordersRouter.post("/", requireAuth, async (req: Request, res: Response) => {
  try {
    const id = uuid();
    const { buyer_id, listing_id, seller_id, quantity, unit_price, total, status } = req.body;
    const state = ORDER_INITIAL;
    const sql = `INSERT INTO orders (id, buyer_id, listing_id, seller_id, quantity, unit_price, total, status, state) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *`;
    const rows = await query(sql, [id, buyer_id, listing_id, seller_id, quantity, unit_price, total, status, state]);
    counter("entity.created", { entity: "Order" });
    res.status(201).json(rows[0]);
  } catch (e: any) {
    res.status(400).json({ error: { code: "CREATE_FAILED", message: e.message } });
  }
});

// READ
ordersRouter.get("/:id", requireAuth, async (req: Request, res: Response) => {
  try {
    const row = await queryOne(`SELECT * FROM orders WHERE id = $1`, [req.params.id]);
    if (!row) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.json(row);
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// LIST
ordersRouter.get("/", requireAuth, async (req: Request, res: Response) => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const pageSize = Math.min(parseInt(req.query.page_size as string) || 50, 100);
    const offset = (page - 1) * pageSize;
    const rows = await query(`SELECT orders.*, row_to_json(listing.*) as listing, row_to_json(buyer.*) as buyer FROM orders LEFT JOIN listings listing ON orders.listing_id = listing.id LEFT JOIN buyers buyer ON orders.buyer_id = buyer.id ORDER BY orders.created_at DESC LIMIT $1 OFFSET $2`, [pageSize, offset]);
    const [{ count }] = await query(`SELECT COUNT(*) as count FROM orders`);
    res.json({ items: rows, total: parseInt(count), page, page_size: pageSize });
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// UPDATE
ordersRouter.put("/:id", requireAuth, async (req: Request, res: Response) => {
  const fields = { ...req.body };
  // State machine enforcement
  if (fields.state !== undefined) {
    const current = await queryOne<{ state: string }>(`SELECT state FROM orders WHERE id = $1`, [req.params.id]);
    if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    const tr = transitionOrder(current.state as any, `${current.state}_to_${fields.state}`);
    if (!tr.ok) return res.status(422).json({ error: { code: "INVALID_TRANSITION", message: tr.error } });
  }
  const sets = Object.keys(fields).map((k, i) => `${k} = $${i + 2}`).join(", ");
  const values = Object.values(fields);
  const sql = `UPDATE orders SET ${sets}, updated_at = NOW() WHERE id = $1 RETURNING *`;
  const rows = await query(sql, [req.params.id, ...values]);
  if (rows.length === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(rows[0]);
});

// DELETE
ordersRouter.delete("/:id", requireAuth, async (req: Request, res: Response) => {
  try {
    const count = await execute(`DELETE FROM orders WHERE id = $1`, [req.params.id]);
    if (count === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.status(204).send();
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// CAPABILITY: process_payment [transactional]
ordersRouter.post("/process-payment", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const order = await queryOne(`SELECT * FROM orders WHERE id = $1`, [req.body.order_id || req.params.id]);
    if (!order) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "order not found" } });
    }
    const buyer = await queryOne(`SELECT * FROM buyers WHERE id = $1`, [req.body.buyer_id || req.params.id]);
    if (!buyer) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "buyer not found" } });
    }

    // Preconditions
    if (!(order?.status === "pending")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "order.status == \\\"pending\\\"" } });
    }
    if (!(order?.buyer_id === buyer?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "order.buyer_id == buyer.id" } });
    }
    if (!(buyer?.balance >= order?.total)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "buyer.balance >= order.total" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE orders SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING *`, ["paid", req.body.order_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: order.status = \"paid\"");
    }
    const __effect_1 = await query(`UPDATE buyers SET balance = balance - $1, updated_at = NOW() WHERE id = $2 RETURNING *`, [order?.total, req.body.buyer_id || req.params.id]);
    if (!__effect_1 || __effect_1.length === 0) {
      throw new Error("Effect failed: buyer.balance -= order.total");
    }

    // Emit events
    await eventBus.publish("PaymentProcessed", { order_id: order?.id, buyer_id: buyer?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "OrderService", auth.trace_id, __client);

    res.json({ ok: true, action: "process_payment", entity: order });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});

// CAPABILITY: ship_order [transactional]
ordersRouter.post("/ship-order", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const seller = await queryOne(`SELECT * FROM sellers WHERE id = $1`, [req.body.seller_id || req.params.id]);
    if (!seller) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "seller not found" } });
    }
    const order = await queryOne(`SELECT * FROM orders WHERE id = $1`, [req.body.order_id || req.params.id]);
    if (!order) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "order not found" } });
    }

    // Preconditions
    if (!(order?.status === "paid")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "order.status == \\\"paid\\\"" } });
    }
    if (!(order?.seller_id === seller?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "order.seller_id == seller.id" } });
    }
    if (!(seller?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "seller.state == \\\"active\\\"" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE orders SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING *`, ["shipped", req.body.order_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: order.status = \"shipped\"");
    }

    // Emit events
    await eventBus.publish("OrderShipped", { seller_id: seller?.id, order_id: order?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "OrderService", auth.trace_id, __client);

    res.json({ ok: true, action: "ship_order", entity: seller });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});

// CAPABILITY: cancel_order [transactional]
ordersRouter.post("/cancel-order", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const order = await queryOne(`SELECT * FROM orders WHERE id = $1`, [req.body.order_id || req.params.id]);
    if (!order) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "order not found" } });
    }

    // Preconditions
    if (!(order?.status === "pending")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "order.status == \\\"pending\\\"" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE orders SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING *`, ["cancelled", req.body.order_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: order.status = \"cancelled\"");
    }

    // Emit events
    await eventBus.publish("OrderCancelled", { order_id: order?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "OrderService", auth.trace_id, __client);

    res.json({ ok: true, action: "cancel_order", entity: order });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});

// CAPABILITY: post_review
ordersRouter.post("/post-review", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  try {
    // sync: eventual — effects applied, events queued via outbox
    const { rating, comment } = req.body;

    // Fetch entities
    const buyer = await queryOne(`SELECT * FROM buyers WHERE id = $1`, [req.body.buyer_id || req.params.id]);
    if (!buyer) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "buyer not found" } });
    }
    const order = await queryOne(`SELECT * FROM orders WHERE id = $1`, [req.body.order_id || req.params.id]);
    if (!order) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "order not found" } });
    }

    // Preconditions
    if (!(order?.status === "delivered")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "order.status == \\\"delivered\\\"" } });
    }
    if (!(order?.buyer_id === buyer?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "order.buyer_id == buyer.id" } });
    }
    if (!(rating >= 1)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "rating >= 1" } });
    }
    if (!(rating <= 5)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "rating <= 5" } });
    }

    // Emit events
    await eventBus.publish("ReviewPosted", { buyer_id: buyer?.id, order_id: order?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "OrderService", auth.trace_id);

    res.json({ ok: true, action: "post_review", entity: buyer });
  } catch (e: any) {
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  }
});
