// Generated by BoneScript compiler. DO NOT EDIT.
// Service: SellerService
import { Router, Request, Response } from "express";
import { v4 as uuid } from "uuid";
import { query, queryOne, execute, pool } from "../db";
import { eventBus } from "../events";
import { requireAuth, AuthContext } from "../auth";
import { logger } from "../logger";
import { counter } from "../metrics";
import * as __algorithms from "../algorithms";
const { shortestPath, topologicalSort, binarySearch, bipartiteMatching, roundRobin, weightedAverage, percentile, rankBy, consistentHash } = __algorithms as any;

import { transitionSeller, SELLER_INITIAL } from "../state_machines/seller";

export const sellersRouter = Router();

// CREATE
sellersRouter.post("/", requireAuth, async (req: Request, res: Response) => {
  try {
    const id = uuid();
    const { name, email, balance, rating } = req.body;
    const state = SELLER_INITIAL;
    const sql = `INSERT INTO sellers (id, name, email, balance, rating, state) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *`;
    const rows = await query(sql, [id, name, email, balance, rating, state]);
    counter("entity.created", { entity: "Seller" });
    res.status(201).json(rows[0]);
  } catch (e: any) {
    res.status(400).json({ error: { code: "CREATE_FAILED", message: e.message } });
  }
});

// READ
sellersRouter.get("/:id", requireAuth, async (req: Request, res: Response) => {
  try {
    const row = await queryOne(`SELECT * FROM sellers WHERE id = $1`, [req.params.id]);
    if (!row) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.json(row);
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// LIST
sellersRouter.get("/", requireAuth, async (req: Request, res: Response) => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const pageSize = Math.min(parseInt(req.query.page_size as string) || 50, 100);
    const offset = (page - 1) * pageSize;
    const rows = await query(`SELECT * FROM sellers ORDER BY created_at DESC LIMIT $1 OFFSET $2`, [pageSize, offset]);
    const [{ count }] = await query(`SELECT COUNT(*) as count FROM sellers`);
    res.json({ items: rows, total: parseInt(count), page, page_size: pageSize });
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// UPDATE
sellersRouter.put("/:id", requireAuth, async (req: Request, res: Response) => {
  const fields = { ...req.body };
  // State machine enforcement
  if (fields.state !== undefined) {
    const current = await queryOne<{ state: string }>(`SELECT state FROM sellers WHERE id = $1`, [req.params.id]);
    if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    const tr = transitionSeller(current.state as any, `${current.state}_to_${fields.state}`);
    if (!tr.ok) return res.status(422).json({ error: { code: "INVALID_TRANSITION", message: tr.error } });
  }
  const sets = Object.keys(fields).map((k, i) => `${k} = $${i + 2}`).join(", ");
  const values = Object.values(fields);
  const sql = `UPDATE sellers SET ${sets}, updated_at = NOW() WHERE id = $1 RETURNING *`;
  const rows = await query(sql, [req.params.id, ...values]);
  if (rows.length === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
  res.json(rows[0]);
});

// DELETE
sellersRouter.delete("/:id", requireAuth, async (req: Request, res: Response) => {
  try {
    const count = await execute(`DELETE FROM sellers WHERE id = $1`, [req.params.id]);
    if (count === 0) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Not found" } });
    res.status(204).send();
  } catch (e: any) {
    res.status(500).json({ error: { code: "DB_ERROR", message: e.message } });
  }
});

// CAPABILITY: publish_listing [transactional]
sellersRouter.post("/publish-listing", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const seller = await queryOne(`SELECT * FROM sellers WHERE id = $1`, [req.body.seller_id || req.params.id]);
    if (!seller) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "seller not found" } });
    }
    const listing = await queryOne(`SELECT * FROM listings WHERE id = $1`, [req.body.listing_id || req.params.id]);
    if (!listing) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "listing not found" } });
    }

    // Preconditions
    if (!(seller?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "seller.state == \\\"active\\\"" } });
    }
    if (!(listing?.state === "draft")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.state == \\\"draft\\\"" } });
    }
    if (!(listing?.seller_id === seller?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.seller_id == seller.id" } });
    }
    if (!(listing?.stock > 0)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.stock > 0" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE listings SET state = $1, updated_at = NOW() WHERE id = $2 RETURNING *`, ["active", req.body.listing_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: listing.state = \"active\"");
    }

    res.json({ ok: true, action: "publish_listing", entity: seller });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});

// CAPABILITY: archive_listing [transactional]
sellersRouter.post("/archive-listing", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const seller = await queryOne(`SELECT * FROM sellers WHERE id = $1`, [req.body.seller_id || req.params.id]);
    if (!seller) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "seller not found" } });
    }
    const listing = await queryOne(`SELECT * FROM listings WHERE id = $1`, [req.body.listing_id || req.params.id]);
    if (!listing) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "listing not found" } });
    }

    // Preconditions
    if (!(seller?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "seller.state == \\\"active\\\"" } });
    }
    if (!(listing?.seller_id === seller?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.seller_id == seller.id" } });
    }
    if (!(listing?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "listing.state == \\\"active\\\"" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE listings SET state = $1, updated_at = NOW() WHERE id = $2 RETURNING *`, ["archived", req.body.listing_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: listing.state = \"archived\"");
    }

    res.json({ ok: true, action: "archive_listing", entity: seller });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});

// CAPABILITY: ship_order [transactional]
sellersRouter.post("/ship-order", requireAuth, async (req: Request, res: Response) => {
  const auth: AuthContext = (req as any).auth;
  const __client = await pool.connect();
  try {
    await __client.query("BEGIN");
    // Fetch entities
    const seller = await queryOne(`SELECT * FROM sellers WHERE id = $1`, [req.body.seller_id || req.params.id]);
    if (!seller) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "seller not found" } });
    }
    const order = await queryOne(`SELECT * FROM orders WHERE id = $1`, [req.body.order_id || req.params.id]);
    if (!order) {
      return res.status(404).json({ error: { code: "NOT_FOUND", message: "order not found" } });
    }

    // Preconditions
    if (!(order?.status === "paid")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "order.status == \\\"paid\\\"" } });
    }
    if (!(order?.seller_id === seller?.id)) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "order.seller_id == seller.id" } });
    }
    if (!(seller?.state === "active")) {
      return res.status(422).json({ error: { code: "PRECONDITION_FAILED", message: "seller.state == \\\"active\\\"" } });
    }

    // Effects (applied in declaration order)
    const __effect_0 = await query(`UPDATE orders SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING *`, ["shipped", req.body.order_id || req.params.id]);
    if (!__effect_0 || __effect_0.length === 0) {
      throw new Error("Effect failed: order.status = \"shipped\"");
    }

    // Emit events
    await eventBus.publish("OrderShipped", { seller_id: seller?.id, order_id: order?.id, timestamp: new Date().toISOString(), actor_id: auth.actor_id }, "SellerService", auth.trace_id, __client);

    res.json({ ok: true, action: "ship_order", entity: seller });
    await __client.query("COMMIT");
  } catch (e: any) {
    await __client.query("ROLLBACK");
    res.status(400).json({ error: { code: "CAPABILITY_FAILED", message: e.message } });
  } finally {
    __client.release();
  }
});
