// Generated by BoneScript compiler. DO NOT EDIT.
// Migration runner with a schema_migrations ledger.
// Each block is hashed at compile time; runs are skipped if the same
// (id, checksum) pair has already been recorded as applied.
require("dotenv").config();
import * as fs from "fs";
import * as path from "path";
import { createHash } from "crypto";
import { pool } from "./db";

interface Block { id: string; checksum: string; sql: string; }

const GENERATED_BLOCKS: Block[] = [
  {
    id: "0000_sellers",
    checksum: "9e00ef04b10cd7a47ca892d5d80c96d8fa838e9df61e1d10cf9dd2133918661e",
    sql: `-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: a67cf6198907a910
-- Module: SellerStore

CREATE TABLE IF NOT EXISTS sellers (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  balance BIGINT NOT NULL,
  rating DOUBLE PRECISION NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE OR REPLACE FUNCTION update_sellers_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sellers_updated_at
  BEFORE UPDATE ON sellers
  FOR EACH ROW
  EXECUTE FUNCTION update_sellers_updated_at();
`,
  },
  {
    id: "0001_listings",
    checksum: "0d4941169c13d60106f72ac18704d9b54dea10599fb0f6e08c8f7a4ed182f2ed",
    sql: `-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: a67cf6198907a910
-- Module: ListingStore

CREATE TABLE IF NOT EXISTS listings (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  seller_id UUID NOT NULL,
  title VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  price BIGINT NOT NULL,
  stock BIGINT NOT NULL,
  category VARCHAR NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE OR REPLACE FUNCTION update_listings_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_listings_updated_at
  BEFORE UPDATE ON listings
  FOR EACH ROW
  EXECUTE FUNCTION update_listings_updated_at();
`,
  },
  {
    id: "0002_buyers",
    checksum: "a5f8d5daa1af9a1195dafc4eb9cf4811a4439a60c7c464f8700be98f2bf5a9f2",
    sql: `-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: a67cf6198907a910
-- Module: BuyerStore

CREATE TABLE IF NOT EXISTS buyers (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  balance BIGINT NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE OR REPLACE FUNCTION update_buyers_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_buyers_updated_at
  BEFORE UPDATE ON buyers
  FOR EACH ROW
  EXECUTE FUNCTION update_buyers_updated_at();
`,
  },
  {
    id: "0003_orders",
    checksum: "407d9bd9da9655dc6495638fbf23960db2f5253076559f2bf80df32bf6ed4acf",
    sql: `-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: a67cf6198907a910
-- Module: OrderStore

CREATE TABLE IF NOT EXISTS orders (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  buyer_id UUID NOT NULL,
  listing_id UUID NOT NULL,
  seller_id UUID NOT NULL,
  quantity BIGINT NOT NULL,
  unit_price BIGINT NOT NULL,
  total BIGINT NOT NULL,
  status VARCHAR NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE OR REPLACE FUNCTION update_orders_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_orders_updated_at();
`,
  },
  {
    id: "0004_reviews",
    checksum: "c32424c09dbaabf7f26d854cdaff126e6706c4aaa6ea12104dea6d477f4f03cb",
    sql: `-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: a67cf6198907a910
-- Module: ReviewService

CREATE TABLE IF NOT EXISTS reviews (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  order_id UUID NOT NULL,
  buyer_id UUID NOT NULL,
  seller_id UUID NOT NULL,
  rating BIGINT NOT NULL,
  comment VARCHAR NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reviews_seller_id_buyer_id ON reviews (seller_id, buyer_id);

CREATE OR REPLACE FUNCTION update_reviews_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reviews_updated_at
  BEFORE UPDATE ON reviews
  FOR EACH ROW
  EXECUTE FUNCTION update_reviews_updated_at();
`,
  },
];

/**
 * Pick up any hand-authored migrations dropped into migrations/_manual/.
 * Files are picked up in lexicographic order; `bonec diff --write` writes
 * them with a numeric prefix so insertion order is stable.
 */
function loadManualBlocks(): Block[] {
  const dir = path.resolve(__dirname, "..", "migrations", "_manual");
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith(".sql"))
    .sort()
    .map(f => {
      const sql = fs.readFileSync(path.join(dir, f), "utf-8");
      return {
        id: "manual_" + f.replace(/\.sql$/, ""),
        checksum: createHash("sha256").update(sql).digest("hex"),
        sql,
      };
    });
}

const LEDGER_DDL = `CREATE TABLE IF NOT EXISTS schema_migrations (
  id           VARCHAR PRIMARY KEY,
  checksum     VARCHAR NOT NULL,
  applied_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  applied_by   VARCHAR NOT NULL DEFAULT current_user,
  duration_ms  INTEGER NOT NULL DEFAULT 0
);`;

async function migrate() {
  const client = await pool.connect();
  let applied = 0, skipped = 0;
  try {
    await client.query(LEDGER_DDL);

    // Generated blocks come first (compile-time schema), then manual diffs.
    const allBlocks: Block[] = [...GENERATED_BLOCKS, ...loadManualBlocks()];

    // Load already-applied entries.
    const existing = await client.query(
      "SELECT id, checksum FROM schema_migrations"
    );
    const rows = existing.rows as Array<{ id: string; checksum: string }>;
    const appliedById = new Map(rows.map(r => [r.id, r.checksum]));

    for (const block of allBlocks) {
      const prior = appliedById.get(block.id);
      if (prior === block.checksum) {
        skipped++;
        continue;
      }
      if (prior && prior !== block.checksum) {
        // Someone changed an already-applied migration. Refuse to proceed —
        // an explicit migration file should be authored instead.
        throw new Error(
          `Migration ${block.id} was previously applied with a different ` +
          `checksum. Generate a new migration via 'bonec diff --write' ` +
          `instead of editing existing schemas.`
        );
      }

      const start = Date.now();
      try {
        await client.query("BEGIN");
        await client.query(block.sql);
        await client.query(
          "INSERT INTO schema_migrations (id, checksum, duration_ms) VALUES ($1, $2, $3)",
          [block.id, block.checksum, Date.now() - start]
        );
        await client.query("COMMIT");
        console.log(`  applied  ${block.id}  (${Date.now() - start}ms)`);
        applied++;
      } catch (e) {
        await client.query("ROLLBACK").catch(() => {});
        throw e;
      }
    }

    console.log(`Migrations complete: ${applied} applied, ${skipped} already up to date.`);
  } finally {
    client.release();
    await pool.end();
  }
}

migrate().catch(e => { console.error(e); process.exit(1); });