// Generated by BoneScript compiler.
// Notification service — fires on event emissions.
// Configure NOTIFY_PROVIDER=resend|sendgrid|log (default: log)
// Set NOTIFY_API_KEY and NOTIFY_FROM_EMAIL in .env

import { SystemEvent } from "./events";

export type NotifyProvider = "resend" | "sendgrid" | "log";

const PROVIDER = (process.env.NOTIFY_PROVIDER || "log") as NotifyProvider;
const API_KEY = process.env.NOTIFY_API_KEY || "";
const FROM_EMAIL = process.env.NOTIFY_FROM_EMAIL || "noreply@example.com";

export interface NotifyMessage {
  to: string;
  subject: string;
  body: string;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const __EMAIL_RE = /^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$/;
function isValidEmail(addr: string): boolean {
  if (!addr || addr.length > 254) return false;
  if (/[\r\n]/.test(addr)) return false;
  return __EMAIL_RE.test(addr);
}

async function sendEmail(msg: NotifyMessage): Promise<void> {
  if (!isValidEmail(msg.to)) {
    throw new Error(`Invalid recipient address: ${msg.to.slice(0, 64)}`);
  }
  if (PROVIDER === "log") {
    console.log(`[notify] ${msg.subject} → ${msg.to}`);
    return;
  }
  if (PROVIDER === "resend") {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { "Authorization": `Bearer ${API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({ from: FROM_EMAIL, to: msg.to, subject: msg.subject, html: msg.body }),
    });
    if (!res.ok) throw new Error(`Resend error: ${res.status}`);
    return;
  }
  if (PROVIDER === "sendgrid") {
    const res = await fetch("https://api.sendgrid.com/v3/mail/send", {
      method: "POST",
      headers: { "Authorization": `Bearer ${API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({ personalizations: [{ to: [{ email: msg.to }] }], from: { email: FROM_EMAIL }, subject: msg.subject, content: [{ type: "text/html", value: msg.body }] }),
    });
    if (!res.ok) throw new Error(`SendGrid error: ${res.status}`);
    return;
  }
}

// Handler for OrderPlaced
export async function notifyOrderPlaced(event: SystemEvent, recipientEmail: string): Promise<void> {
  const __payload = escapeHtml(JSON.stringify(event.payload, null, 2));
  await sendEmail({
    to: recipientEmail,
    subject: "OrderPlaced notification",
    body: `<p>Event <strong>${escapeHtml("OrderPlaced")}</strong> occurred.</p><pre>${__payload}</pre>`,
  });
}

// Handler for PaymentProcessed
export async function notifyPaymentProcessed(event: SystemEvent, recipientEmail: string): Promise<void> {
  const __payload = escapeHtml(JSON.stringify(event.payload, null, 2));
  await sendEmail({
    to: recipientEmail,
    subject: "PaymentProcessed notification",
    body: `<p>Event <strong>${escapeHtml("PaymentProcessed")}</strong> occurred.</p><pre>${__payload}</pre>`,
  });
}

// Handler for OrderShipped
export async function notifyOrderShipped(event: SystemEvent, recipientEmail: string): Promise<void> {
  const __payload = escapeHtml(JSON.stringify(event.payload, null, 2));
  await sendEmail({
    to: recipientEmail,
    subject: "OrderShipped notification",
    body: `<p>Event <strong>${escapeHtml("OrderShipped")}</strong> occurred.</p><pre>${__payload}</pre>`,
  });
}

// Handler for OrderCancelled
export async function notifyOrderCancelled(event: SystemEvent, recipientEmail: string): Promise<void> {
  const __payload = escapeHtml(JSON.stringify(event.payload, null, 2));
  await sendEmail({
    to: recipientEmail,
    subject: "OrderCancelled notification",
    body: `<p>Event <strong>${escapeHtml("OrderCancelled")}</strong> occurred.</p><pre>${__payload}</pre>`,
  });
}

// Handler for ReviewPosted
export async function notifyReviewPosted(event: SystemEvent, recipientEmail: string): Promise<void> {
  const __payload = escapeHtml(JSON.stringify(event.payload, null, 2));
  await sendEmail({
    to: recipientEmail,
    subject: "ReviewPosted notification",
    body: `<p>Event <strong>${escapeHtml("ReviewPosted")}</strong> occurred.</p><pre>${__payload}</pre>`,
  });
}

export function registerNotificationHandlers(eventBus: any): void {
  // TODO: implement recipient lookup per event type
  // eventBus.subscribe("OrderPlaced", async (event: SystemEvent) => {
  //   const recipientEmail = await lookupRecipient(event);
  //   await notifyOrderPlaced(event, recipientEmail);
  // });
  // eventBus.subscribe("PaymentProcessed", async (event: SystemEvent) => {
  //   const recipientEmail = await lookupRecipient(event);
  //   await notifyPaymentProcessed(event, recipientEmail);
  // });
  // eventBus.subscribe("OrderShipped", async (event: SystemEvent) => {
  //   const recipientEmail = await lookupRecipient(event);
  //   await notifyOrderShipped(event, recipientEmail);
  // });
  // eventBus.subscribe("OrderCancelled", async (event: SystemEvent) => {
  //   const recipientEmail = await lookupRecipient(event);
  //   await notifyOrderCancelled(event, recipientEmail);
  // });
  // eventBus.subscribe("ReviewPosted", async (event: SystemEvent) => {
  //   const recipientEmail = await lookupRecipient(event);
  //   await notifyReviewPosted(event, recipientEmail);
  // });
}
