-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: e802668954ec5c1f
-- Module: BuyerStore

CREATE TABLE IF NOT EXISTS buyer_stores (
  id UUID NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  balance BIGINT NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);


CREATE OR REPLACE FUNCTION update_buyer_stores_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_buyer_stores_updated_at
  BEFORE UPDATE ON buyer_stores
  FOR EACH ROW
  EXECUTE FUNCTION update_buyer_stores_updated_at();
