-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: e802668954ec5c1f
-- Module: ListingStore

CREATE TABLE IF NOT EXISTS listing_stores (
  id UUID NOT NULL PRIMARY KEY,
  seller_id UUID NOT NULL,
  title VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  price BIGINT NOT NULL,
  stock BIGINT NOT NULL,
  category VARCHAR NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);


CREATE OR REPLACE FUNCTION update_listing_stores_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_listing_stores_updated_at
  BEFORE UPDATE ON listing_stores
  FOR EACH ROW
  EXECUTE FUNCTION update_listing_stores_updated_at();
