-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: e802668954ec5c1f
-- Module: OrderStore

CREATE TABLE IF NOT EXISTS order_stores (
  id UUID NOT NULL PRIMARY KEY,
  buyer_id UUID NOT NULL,
  listing_id UUID NOT NULL,
  seller_id UUID NOT NULL,
  quantity BIGINT NOT NULL,
  unit_price BIGINT NOT NULL,
  total BIGINT NOT NULL,
  status VARCHAR NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);


CREATE OR REPLACE FUNCTION update_order_stores_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_order_stores_updated_at
  BEFORE UPDATE ON order_stores
  FOR EACH ROW
  EXECUTE FUNCTION update_order_stores_updated_at();
