/**
 * BoneScript Auth Emitter
 * Generates auth.ts — JWT middleware with production safety checks.
 */

import * as IR from "./ir";

export function emitAuthMiddleware(_system: IR.IRSystem): string {
  return `// Generated by BoneScript compiler. DO NOT EDIT.
import { Request, Response, NextFunction } from "express";
import jwt from "jsonwebtoken";

// JWT_SECRET must be set in production. The server will refuse to start without it
// when NODE_ENV is "production" to prevent accidental use of a weak fallback.
const JWT_SECRET = (() => {
  const secret = process.env.JWT_SECRET;
  if (!secret) {
    if (process.env.NODE_ENV === "production") {
      console.error("[FATAL] JWT_SECRET environment variable is not set. Refusing to start in production.");
      process.exit(1);
    }
    console.warn("[WARN] JWT_SECRET is not set. Using insecure default — do not use in production.");
    return "bonescript-dev-secret-do-not-use-in-production";
  }
  if (secret.length < 32) {
    console.warn("[WARN] JWT_SECRET is shorter than 32 characters. Use a longer secret in production.");
  }
  return secret;
})();

export interface AuthContext {
  authenticated: boolean;
  actor_id: string | null;
  trace_id: string;
}

export function authMiddleware(req: Request, res: Response, next: NextFunction): void {
  const header = req.headers.authorization;
  if (!header || !header.startsWith("Bearer ")) {
    (req as any).auth = { authenticated: false, actor_id: null, trace_id: req.headers["x-trace-id"] as string || "" };
    next();
    return;
  }
  try {
    const token = header.slice(7);
    const decoded = jwt.verify(token, JWT_SECRET) as { sub: string };
    (req as any).auth = {
      authenticated: true,
      actor_id: decoded.sub,
      trace_id: req.headers["x-trace-id"] as string || "",
    };
  } catch {
    (req as any).auth = { authenticated: false, actor_id: null, trace_id: req.headers["x-trace-id"] as string || "" };
  }
  next();
}

export function requireAuth(req: Request, res: Response, next: NextFunction): void {
  const auth: AuthContext = (req as any).auth;
  if (!auth || !auth.authenticated) {
    res.status(401).json({ error: { code: "UNAUTHORIZED", message: "Authentication required" } });
    return;
  }
  next();
}
`;
}
