/**
 * BoneScript Server Entry Point Emitter
 * Generates src/index.ts — the Express server with all middleware and routes wired.
 */

import * as IR from "./ir";
import { toSnakeCase, toCamelCase } from "./emit_router";

export function emitIndex(system: IR.IRSystem): string {
  const apiModules = system.modules.filter(m => m.kind === "api_service");
  const hasWebSocket = system.modules.some(m => m.kind === "realtime_service");
  const hasBatch = system.modules.some(m =>
    m.interfaces.some(i => i.methods.some(mth => mth.sync === "batch"))
  );
  const lines: string[] = [];

  lines.push(`// Generated by BoneScript compiler. DO NOT EDIT.`);
  lines.push(`// System: ${system.name}`);
  lines.push(`require("dotenv").config();`);
  lines.push(`import express from "express";`);
  lines.push(`import { createServer } from "http";`);
  lines.push(`import cors from "cors";`);
  lines.push(`import helmet from "helmet";`);
  lines.push(`import rateLimit from "express-rate-limit";`);
  lines.push(`import { authMiddleware } from "./auth";`);
  lines.push(`import { healthRouter } from "./health";`);
  lines.push(`import { logger } from "./logger";`);
  lines.push(`import { eventBus } from "./events";`);
  lines.push(`import { pool } from "./db";`);
  if (hasBatch)     lines.push(`import { startBatchWorker } from "./batch";`);
  if (hasWebSocket) lines.push(`import { setupWebSocketServer } from "./websocket";`);
  lines.push(``);

  for (const mod of apiModules) {
    const model = mod.models[0];
    if (!model) continue;
    const routerName = toCamelCase(toSnakeCase(model.name) + "s") + "Router";
    lines.push(`import { ${routerName} } from "./routes/${toSnakeCase(model.name)}";`);
  }

  lines.push(``);
  lines.push(`const app = express();`);
  lines.push(`const httpServer = createServer(app);`);
  lines.push(`const PORT = parseInt(process.env.PORT || "3000");`);
  lines.push(``);

  // Middleware
  lines.push(`// Middleware`);
  lines.push(`app.use(helmet());`);
  lines.push(`// CORS: restrict to ALLOWED_ORIGINS env var (comma-separated). Defaults to same-origin only.`);
  lines.push(`const __allowedOrigins = (process.env.ALLOWED_ORIGINS || "").split(",").map(s => s.trim()).filter(Boolean);`);
  lines.push(`app.use(cors({`);
  lines.push(`  origin: __allowedOrigins.length > 0`);
  lines.push(`    ? (origin, cb) => { if (!origin || __allowedOrigins.includes(origin)) cb(null, true); else cb(new Error("Not allowed by CORS")); }`);
  lines.push(`    : false,`);
  lines.push(`  credentials: true,`);
  lines.push(`}));`);
  lines.push(`app.use(express.json({ limit: "1mb" }));`);
  lines.push(`app.use(express.urlencoded({ extended: false, limit: "1mb" }));`);
  lines.push(`app.use(authMiddleware);`);
  lines.push(``);

  // Rate limiting
  const gw = system.modules.find(m => m.kind === "gateway");
  const rateVal = gw?.config["rate_limit"] || 300;
  lines.push(`// Global rate limit (default ${rateVal} req/min, override with RATE_LIMIT_MAX env var)`);
  lines.push(`const __globalRateLimit = rateLimit({`);
  lines.push(`  windowMs: parseInt(process.env.RATE_LIMIT_WINDOW_MS || "60000"),`);
  lines.push(`  max: parseInt(process.env.RATE_LIMIT_MAX || "${rateVal}"),`);
  lines.push(`  standardHeaders: true,`);
  lines.push(`  legacyHeaders: false,`);
  lines.push(`  message: { error: { code: "RATE_LIMITED", message: "Too many requests, please slow down." } },`);
  lines.push(`});`);
  lines.push(`app.use(__globalRateLimit);`);
  lines.push(``);
  lines.push(`// Strict rate limit on auth endpoints (20 req/min per IP)`);
  lines.push(`const __authRateLimit = rateLimit({`);
  lines.push(`  windowMs: 60000,`);
  lines.push(`  max: parseInt(process.env.AUTH_RATE_LIMIT_MAX || "20"),`);
  lines.push(`  standardHeaders: true,`);
  lines.push(`  legacyHeaders: false,`);
  lines.push(`  message: { error: { code: "RATE_LIMITED", message: "Too many auth attempts." } },`);
  lines.push(`});`);
  lines.push(``);

  // Request timeout
  lines.push(`// Request timeout (default 30s, override per-route)`);
  lines.push(`app.use((req: any, res: any, next: any) => {`);
  lines.push(`  const timeout = parseInt(process.env.REQUEST_TIMEOUT_MS || "30000");`);
  lines.push(`  const timer = setTimeout(() => {`);
  lines.push(`    if (!res.headersSent) {`);
  lines.push(`      res.status(503).json({ error: { code: "REQUEST_TIMEOUT", message: "Request timed out" } });`);
  lines.push(`    }`);
  lines.push(`  }, timeout);`);
  lines.push(`  res.on("finish", () => clearTimeout(timer));`);
  lines.push(`  next();`);
  lines.push(`});`);
  lines.push(``);

  // Routes
  lines.push(`// Health & metrics`);
  lines.push(`app.use("/health", healthRouter);`);
  lines.push(``);
  lines.push(`// Routes`);
  for (const mod of apiModules) {
    const model = mod.models[0];
    if (!model) continue;
    const routerName = toCamelCase(toSnakeCase(model.name) + "s") + "Router";
    const routePath = `/${toSnakeCase(model.name)}s`;
    lines.push(`app.use("${routePath}", ${routerName});`);
    lines.push(`app.use("${routePath}/login", __authRateLimit);`);
    lines.push(`app.use("${routePath}/register", __authRateLimit);`);
  }
  lines.push(``);

  if (hasWebSocket) {
    lines.push(`// WebSocket`);
    lines.push(`setupWebSocketServer(httpServer);`);
    lines.push(``);
  }

  // Startup
  lines.push(`// Start`);
  lines.push(`httpServer.listen(PORT, () => {`);
  lines.push(`  logger.info("server_started", { event: "startup", metadata: { port: PORT } });`);
  lines.push(`  eventBus.startWorker(parseInt(process.env.EVENT_WORKER_INTERVAL_MS || "1000"));`);
  if (hasBatch) lines.push(`  startBatchWorker();`);
  lines.push(`  console.log(\`[${system.name}] Running on port \${PORT}\`);`);
  lines.push(`  console.log(\`  HTTP routes:\`);`);
  for (const mod of apiModules) {
    const model = mod.models[0];
    if (!model) continue;
    lines.push(`  console.log(\`    /${toSnakeCase(model.name)}s\`);`);
  }
  if (hasWebSocket) lines.push(`  console.log(\`  WebSocket: /ws?channel=<name>&token=<jwt>\`);`);
  lines.push(`  console.log(\`  Health: /health/live, /health/ready, /health/metrics\`);`);
  lines.push(`});`);
  lines.push(``);

  // Graceful shutdown
  lines.push(`// Graceful shutdown`);
  lines.push(`const shutdown = async (signal: string) => {`);
  lines.push(`  logger.info("server_stopping", { event: "shutdown", metadata: { signal } });`);
  lines.push(`  httpServer.close(async () => {`);
  lines.push(`    try {`);
  lines.push(`      await pool.end();`);
  lines.push(`      logger.info("server_stopped", { event: "shutdown", status: "success" });`);
  lines.push(`    } catch (e: any) {`);
  lines.push(`      logger.error("shutdown_error", { event: "shutdown", metadata: { error: e.message } });`);
  lines.push(`    }`);
  lines.push(`    process.exit(0);`);
  lines.push(`  });`);
  lines.push(`  setTimeout(() => { logger.error("shutdown_timeout", { event: "shutdown" }); process.exit(1); }, 10000);`);
  lines.push(`};`);
  lines.push(`process.on("SIGTERM", () => shutdown("SIGTERM"));`);
  lines.push(`process.on("SIGINT",  () => shutdown("SIGINT"));`);
  lines.push(``);
  lines.push(`export { app, httpServer };`);

  return lines.join("\n");
}
