/**
 * BoneScript Database Emitter
 * Generates db.ts (connection pool) and migrate.ts (migration runner).
 */

import * as IR from "./ir";
import { toSnakeCase } from "./lowering_helpers";

export function emitDbClient(system: IR.IRSystem): string {
  const name = toSnakeCase(system.name);
  return [
    "// Generated by BoneScript compiler. DO NOT EDIT.",
    `import { Pool, PoolClient } from "pg";`,
    "",
    "// Lazy pool — created on first use so DATABASE_URL is read after dotenv loads",
    "let _pool: Pool | null = null;",
    "function getPool(): Pool {",
    "  if (!_pool) {",
    `    _pool = new Pool({ connectionString: process.env.DATABASE_URL || "postgresql://localhost:5432/${name}", max: 20 });`,
    `    _pool.on("error", (err: Error) => console.error("[DB] Pool error (non-fatal):", err.message));`,
    "  }",
    "  return _pool;",
    "}",
    "export const pool = new Proxy({} as Pool, { get(_t: any, p: any) { return (getPool() as any)[p]; } });",
    "",
    "export async function query<T = any>(text: string, params?: any[]): Promise<T[]> {",
    "  try { const result = await pool.query(text, params); return result.rows as T[]; }",
    "  catch (e: any) { throw new Error(`DB query failed: ${e.message}`); }",
    "}",
    "export async function queryOne<T = any>(text: string, params?: any[]): Promise<T | null> {",
    "  try { const rows = await query<T>(text, params); return rows[0] || null; }",
    "  catch (e: any) { throw new Error(`DB query failed: ${e.message}`); }",
    "}",
    "export async function execute(text: string, params?: any[]): Promise<number> {",
    "  try { const result = await pool.query(text, params); return result.rowCount || 0; }",
    "  catch (e: any) { throw new Error(`DB execute failed: ${e.message}`); }",
    "}",
    "export async function transaction<T>(fn: (client: PoolClient) => Promise<T>): Promise<T> {",
    "  const client = await pool.connect();",
    `  try { await client.query("BEGIN"); const result = await fn(client); await client.query("COMMIT"); return result; }`,
    `  catch (e) { await client.query("ROLLBACK"); throw e; }`,
    "  finally { client.release(); }",
    "}",
  ].join("\n");
}

export function emitMigration(system: IR.IRSystem, schemas: string[]): string {
  const lines: string[] = [];
  lines.push(`// Generated by BoneScript compiler. DO NOT EDIT.`);
  lines.push(`require("dotenv").config();`);
  lines.push(`import { pool } from "./db";`);
  lines.push(``);
  lines.push(`async function migrate() {`);
  lines.push(`  console.log("Running migrations...");`);
  lines.push(`  const client = await pool.connect();`);
  lines.push(`  try {`);

  for (const schema of schemas) {
    const escaped = schema.replace(/`/g, "\\`").replace(/\$/g, "\\$");
    lines.push(`    await client.query(\`${escaped}\`);`);
  }

  lines.push(`    console.log("Migrations complete.");`);
  lines.push(`  } finally {`);
  lines.push(`    client.release();`);
  lines.push(`    await pool.end();`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`migrate().catch(e => { console.error(e); process.exit(1); });`);
  return lines.join("\n");
}
