/**
 * BoneScript Model Emitter
 * Generates per-model TypeScript artifacts as specified in spec/09_CODEGEN.md §5.1:
 *   - XxxInterface  — typed interface
 *   - XxxSchema     — const with field metadata (type, nullable, unique, indexed)
 *   - validateXxx() — runtime validation function derived from IR constraints
 *
 * These are emitted to src/models/<entity_name>.ts
 */

import * as IR from "./ir";
import { toTsType, toSnakeCase } from "./emit_router";

// ─── Per-model file ───────────────────────────────────────────────────────────

export function emitModelFile(model: IR.IRModel, mod: IR.IRModule, system: IR.IRSystem): string {
  const lines: string[] = [];
  lines.push(`// Generated by BoneScript compiler. DO NOT EDIT.`);
  lines.push(`// Source hash: ${system.source_hash}`);
  lines.push(`// Module: ${mod.name}`);
  lines.push(``);

  // ── Interface ──────────────────────────────────────────────────────────────
  lines.push(`export interface ${model.name} {`);
  for (const field of model.fields) {
    // Skip generated-always fields (derived columns)
    if (field.default_value?.startsWith("GENERATED ALWAYS")) continue;
    const nullable = field.nullable ? " | null" : "";
    lines.push(`  ${field.name}: ${toTsType(field.type)}${nullable};`);
  }
  lines.push(`}`);
  lines.push(``);

  // ── Schema const ───────────────────────────────────────────────────────────
  lines.push(`export const ${model.name}Schema = {`);
  for (const field of model.fields) {
    if (field.default_value?.startsWith("GENERATED ALWAYS")) continue;
    const meta: string[] = [
      `type: ${JSON.stringify(field.type)}`,
      `nullable: ${field.nullable}`,
      `unique: ${field.unique}`,
      `indexed: ${field.indexed}`,
    ];
    if (field.default_value && !field.default_value.startsWith("GENERATED")) {
      meta.push(`default: ${JSON.stringify(field.default_value)}`);
    }
    lines.push(`  ${field.name}: { ${meta.join(", ")} },`);
  }
  lines.push(`} as const;`);
  lines.push(``);

  // ── Input type (omits server-set fields) ──────────────────────────────────
  const inputFields = model.fields.filter(f =>
    !["id", "created_at", "updated_at"].includes(f.name) &&
    !f.default_value?.startsWith("GENERATED ALWAYS")
  );
  lines.push(`export interface Create${model.name}Input {`);
  for (const field of inputFields) {
    const nullable = field.nullable ? "?" : "";
    lines.push(`  ${field.name}${nullable}: ${toTsType(field.type)};`);
  }
  lines.push(`}`);
  lines.push(``);

  lines.push(`export interface Update${model.name}Input {`);
  for (const field of inputFields) {
    lines.push(`  ${field.name}?: ${toTsType(field.type)};`);
  }
  lines.push(`}`);
  lines.push(``);

  // ── Validation function ────────────────────────────────────────────────────
  lines.push(`export interface ValidationError {`);
  lines.push(`  field: string;`);
  lines.push(`  code: string;`);
  lines.push(`  message: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function validate${model.name}(input: unknown): { ok: true; value: ${model.name} } | { ok: false; errors: ValidationError[] } {`);
  lines.push(`  const errors: ValidationError[] = [];`);
  lines.push(`  const data = input as Record<string, unknown>;`);
  lines.push(``);

  // Required field presence checks
  for (const field of model.fields) {
    if (field.nullable || field.default_value || ["id", "created_at", "updated_at"].includes(field.name)) continue;
    if (field.default_value?.startsWith("GENERATED ALWAYS")) continue;
    lines.push(`  if (data.${field.name} === undefined || data.${field.name} === null) {`);
    lines.push(`    errors.push({ field: "${field.name}", code: "REQUIRED", message: "${field.name} is required" });`);
    lines.push(`  }`);
  }

  // Type checks for primitive fields
  for (const field of model.fields) {
    if (["id", "created_at", "updated_at"].includes(field.name)) continue;
    if (field.default_value?.startsWith("GENERATED ALWAYS")) continue;
    const check = typeCheckExpr(field.type, `data.${field.name}`);
    if (check) {
      lines.push(`  if (data.${field.name} !== undefined && data.${field.name} !== null && !(${check})) {`);
      lines.push(`    errors.push({ field: "${field.name}", code: "INVALID_TYPE", message: "${field.name} must be ${field.type}" });`);
      lines.push(`  }`);
    }
  }

  // Constraint-derived checks from model constraints
  for (const c of model.constraints) {
    if (c.kind === "unique") continue; // enforced by DB
    if (c.kind === "range" && c.params["min"] !== undefined && c.params["max"] !== undefined) {
      lines.push(`  if (typeof data.${c.target} === "number" && (data.${c.target} < ${c.params["min"]} || data.${c.target} > ${c.params["max"]})) {`);
      lines.push(`    errors.push({ field: "${c.target}", code: "OUT_OF_RANGE", message: "${c.target} must be between ${c.params["min"]} and ${c.params["max"]}" });`);
      lines.push(`  }`);
    }
    if (c.kind === "enum" && Array.isArray(c.params["values"])) {
      const vals = (c.params["values"] as string[]).map(v => JSON.stringify(v)).join(", ");
      lines.push(`  if (data.${c.target} !== undefined && ![${vals}].includes(data.${c.target} as string)) {`);
      lines.push(`    errors.push({ field: "${c.target}", code: "INVALID_ENUM", message: "${c.target} must be one of: ${(c.params["values"] as string[]).join(", ")}" });`);
      lines.push(`  }`);
    }
    if (c.kind === "check" && typeof c.params["expression"] === "string") {
      // Parse length-in-range constraints like "username.length in 3..32"
      const lenMatch = (c.params["expression"] as string).match(/^(\w+)\.length\s+in\s+(\d+)\.\.(\d+)$/);
      if (lenMatch) {
        const [, fieldName, minLen, maxLen] = lenMatch;
        lines.push(`  if (typeof data.${fieldName} === "string" && (data.${fieldName}.length < ${minLen} || data.${fieldName}.length > ${maxLen})) {`);
        lines.push(`    errors.push({ field: "${fieldName}", code: "INVALID_LENGTH", message: "${fieldName} must be between ${minLen} and ${maxLen} characters" });`);
        lines.push(`  }`);
      }
      // Parse non-negative constraints like "score >= 0"
      const nonNegMatch = (c.params["expression"] as string).match(/^(\w+)\s*>=\s*0$/);
      if (nonNegMatch) {
        const [, fieldName] = nonNegMatch;
        lines.push(`  if (typeof data.${fieldName} === "number" && data.${fieldName} < 0) {`);
        lines.push(`    errors.push({ field: "${fieldName}", code: "OUT_OF_RANGE", message: "${fieldName} must be >= 0" });`);
        lines.push(`  }`);
      }
    }
  }

  lines.push(``);
  lines.push(`  if (errors.length > 0) return { ok: false, errors };`);
  lines.push(`  return { ok: true, value: data as unknown as ${model.name} };`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

function typeCheckExpr(irType: string, expr: string): string | null {
  switch (irType) {
    case "string":    return `typeof ${expr} === "string"`;
    case "uint":      return `typeof ${expr} === "number" && Number.isInteger(${expr}) && ${expr} >= 0`;
    case "int":       return `typeof ${expr} === "number" && Number.isInteger(${expr})`;
    case "float":     return `typeof ${expr} === "number"`;
    case "bool":      return `typeof ${expr} === "boolean"`;
    case "uuid":      return `typeof ${expr} === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(${expr})`;
    case "timestamp": return `${expr} instanceof Date || typeof ${expr} === "string"`;
    default:
      if (irType.startsWith("list<") || irType.startsWith("set<")) return `Array.isArray(${expr})`;
      return null;
  }
}

// ─── Barrel index for all models ─────────────────────────────────────────────

export function emitModelsIndex(system: IR.IRSystem): string {
  const lines: string[] = [];
  lines.push(`// Generated by BoneScript compiler. DO NOT EDIT.`);
  lines.push(`// Re-exports all model interfaces, schemas, and validators.`);
  lines.push(``);
  for (const mod of system.modules) {
    for (const model of mod.models) {
      lines.push(`export * from "./${toSnakeCase(model.name)}";`);
    }
  }
  return lines.join("\n");
}
