/**
 * BoneScript Code Emitter â€” Stage 6 of the compilation pipeline.
 * Implements spec/09_CODEGEN.md.
 *
 * Generates target code from the IR. Every IR node maps to code.
 * No orphan logic. No hidden behavior. Deterministic formatting.
 */

import * as IR from "./ir";
import { emitCapabilityBody } from "./emit_capability";
import { emitPipelineBody, emitAlgorithmBody } from "./emit_composition";
import { toSnakeCase } from "./lowering_helpers";
import { toTsType } from "./emit_router";

export interface EmittedFile {
  path: string;
  content: string;
  language: "typescript" | "sql" | "yaml" | "json";
  source_module: string;
}

// â”€â”€â”€ Type Mapping â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

const TS_TYPE_MAP: Record<string, string> = {
  string: "string",
  uint: "number",
  int: "number",
  float: "number",
  bool: "boolean",
  timestamp: "Date",
  uuid: "string",
  bytes: "Buffer",
  json: "unknown",
};

const SQL_TYPE_MAP: Record<string, string> = {
  string: "VARCHAR",
  uint: "BIGINT",
  int: "BIGINT",
  float: "DOUBLE PRECISION",
  bool: "BOOLEAN",
  timestamp: "TIMESTAMPTZ",
  uuid: "UUID",
  bytes: "BYTEA",
  json: "JSONB",
};


function toSqlType(irType: string): string {
  if (SQL_TYPE_MAP[irType]) return SQL_TYPE_MAP[irType];
  if (irType.startsWith("list<") || irType.startsWith("set<") || irType.startsWith("map<")) return "JSONB";
  if (irType.startsWith("optional<")) return toSqlType(irType.slice(9, -1));
  return "JSONB";
}

/** Returns an inline SQL CHECK constraint for types that need one, or empty string. */
function sqlCheckConstraint(irType: string): string {
  if (irType === "uint") return " CHECK (VALUE >= 0)";
  return "";
}


// â”€â”€â”€ Emitter â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export class Emitter {
  emit(system: IR.IRSystem): EmittedFile[] {
    const files: EmittedFile[] = [];

    // 1. Schema files (SQL)
    for (const mod of system.modules) {
      if (mod.kind === "data_store" || mod.kind === "api_service") {
        for (const model of mod.models) {
          files.push(this.emitSchema(model, mod, system));
        }
      }
    }

    // 2. Type definition files (TypeScript)
    files.push(this.emitSharedTypes(system));

    // 3. Event types (TypeScript)
    if (system.events.length > 0) {
      files.push(this.emitEventTypes(system));
    }

    // 4. Service files (TypeScript)
    for (const mod of system.modules) {
      if (mod.kind === "api_service") {
        files.push(this.emitService(mod, system));
      }
    }

    // 5. State machine files (TypeScript)
    for (const mod of system.modules) {
      for (const sm of mod.state_machines) {
        files.push(this.emitStateMachine(sm, mod, system));
      }
    }

    // 6. Config files (YAML)
    files.push(this.emitServiceConfig(system));

    // 7. Infrastructure config (YAML)
    files.push(this.emitInfraConfig(system));

    return files;
  }

  // â”€â”€â”€ SQL Schema â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  private emitSchema(model: IR.IRModel, mod: IR.IRModule, system: IR.IRSystem): EmittedFile {
    const tableName = toSnakeCase(model.name) + "s";
    const lines: string[] = [];

    lines.push(`-- Generated by BoneScript compiler. DO NOT EDIT.`);
    lines.push(`-- Source: ${system.source_hash}`);
    lines.push(`-- Module: ${mod.name}`);
    lines.push(``);
    lines.push(`CREATE TABLE IF NOT EXISTS ${tableName} (`);

    const fieldLines: string[] = [];
    for (const field of model.fields) {
      let line = `  ${field.name} ${toSqlType(field.type)}${sqlCheckConstraint(field.type)}`;
      if (!field.nullable) line += " NOT NULL";
      if (field.default_value) {
        if (field.default_value === "gen_random_uuid()") line += " DEFAULT gen_random_uuid()";
        else if (field.default_value === "now()") line += " DEFAULT NOW()";
        else line += ` DEFAULT ${field.default_value}`;
      } else if (field.name === "created_at" || field.name === "updated_at") {
        // Always add DEFAULT NOW() for timestamp audit fields
        line += " DEFAULT NOW()";
      } else if (field.name === "id" && field.type === "uuid") {
        // Always add DEFAULT gen_random_uuid() for uuid primary keys
        line += " DEFAULT gen_random_uuid()";
      }
      if (field.name === model.primary_key) line += " PRIMARY KEY";
      fieldLines.push(line);
    }

    // Add unique constraints
    for (const c of model.constraints) {
      if (c.kind === "unique") {
        fieldLines.push(`  CONSTRAINT ${tableName}_${c.target}_unique UNIQUE (${c.target})`);
      }
    }

    // Add foreign key constraints from relations
    for (const rel of mod.relations || []) {
      if (rel.kind === "belongs_to") {
        // belongs_to: FK is on this table
        fieldLines.push(`  CONSTRAINT fk_${tableName}_${rel.foreign_key} FOREIGN KEY (${rel.foreign_key}) REFERENCES ${rel.to_table}(id) ON DELETE CASCADE`);
      }
    }

    // Add cardinality CHECK constraints from relations
    // has_one: enforce at most 1 child row via a partial unique index (emitted below)
    // has_many with explicit max: enforce via CHECK on count (done via trigger — see below)

    lines.push(fieldLines.join(",\n"));
    lines.push(`);`);
    lines.push(``);

    // Indexes
    for (const idx of model.indexes) {
      const idxName = `idx_${tableName}_${idx.fields.join("_")}`;
      const unique = idx.unique ? "UNIQUE " : "";
      lines.push(`CREATE ${unique}INDEX IF NOT EXISTS ${idxName} ON ${tableName} (${idx.fields.join(", ")});`);
    }

    // FK indexes for belongs_to relations
    for (const rel of mod.relations || []) {
      if (rel.kind === "belongs_to") {
        lines.push(`CREATE INDEX IF NOT EXISTS idx_${tableName}_${rel.foreign_key} ON ${tableName} (${rel.foreign_key});`);
      }
    }

    // Cardinality enforcement
    for (const rel of mod.relations || []) {
      // has_one: enforce via unique index on the FK column in the child table
      if (rel.kind === "has_one") {
        const childTable = rel.to_table;
        const fk = rel.foreign_key;
        lines.push(``);
        lines.push(`-- has_one cardinality: each ${tableName.slice(0, -1)} may have at most one ${childTable.slice(0, -1)}`);
        lines.push(`CREATE UNIQUE INDEX IF NOT EXISTS idx_${childTable}_${fk}_unique ON ${childTable} (${fk});`);
      }

      // has_many with explicit numeric max: enforce via a BEFORE INSERT trigger
      if (rel.kind === "has_many" && rel.cardinality && rel.cardinality.max !== "*") {
        const maxCount = rel.cardinality.max as number;
        const childTable = rel.to_table;
        const fk = rel.foreign_key;
        const fnName = `check_${tableName}_${rel.name}_max`;
        lines.push(``);
        lines.push(`-- has_many cardinality: max ${maxCount} ${childTable} per ${tableName.slice(0, -1)}`);
        lines.push(`CREATE OR REPLACE FUNCTION ${fnName}()`);
        lines.push(`RETURNS TRIGGER AS $$`);
        lines.push(`DECLARE`);
        lines.push(`  current_count INTEGER;`);
        lines.push(`BEGIN`);
        lines.push(`  SELECT COUNT(*) INTO current_count FROM ${childTable} WHERE ${fk} = NEW.${fk};`);
        lines.push(`  IF current_count >= ${maxCount} THEN`);
        lines.push(`    RAISE EXCEPTION 'Cardinality violation: ${tableName.slice(0, -1)} already has ${maxCount} ${childTable} (max ${maxCount})';`);
        lines.push(`  END IF;`);
        lines.push(`  RETURN NEW;`);
        lines.push(`END;`);
        lines.push(`$$ LANGUAGE plpgsql;`);
        lines.push(``);
        lines.push(`DROP TRIGGER IF EXISTS trg_${fnName} ON ${childTable};`);
        lines.push(`CREATE TRIGGER trg_${fnName}`);
        lines.push(`  BEFORE INSERT ON ${childTable}`);
        lines.push(`  FOR EACH ROW`);
        lines.push(`  EXECUTE FUNCTION ${fnName}();`);
      }
    }

    // Junction tables for many_to_many
    for (const rel of mod.relations || []) {
      if (rel.kind === "many_to_many" && rel.junction_table) {
        lines.push(``);
        lines.push(`CREATE TABLE IF NOT EXISTS ${rel.junction_table} (`);
        lines.push(`  ${rel.from_table.slice(0, -1)}_id UUID NOT NULL REFERENCES ${rel.from_table}(id) ON DELETE CASCADE,`);
        lines.push(`  ${rel.to_table.slice(0, -1)}_id UUID NOT NULL REFERENCES ${rel.to_table}(id) ON DELETE CASCADE,`);
        lines.push(`  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),`);
        lines.push(`  PRIMARY KEY (${rel.from_table.slice(0, -1)}_id, ${rel.to_table.slice(0, -1)}_id)`);
        lines.push(`);`);
        lines.push(`CREATE INDEX IF NOT EXISTS idx_${rel.junction_table}_${rel.from_table.slice(0, -1)} ON ${rel.junction_table} (${rel.from_table.slice(0, -1)}_id);`);
        lines.push(`CREATE INDEX IF NOT EXISTS idx_${rel.junction_table}_${rel.to_table.slice(0, -1)} ON ${rel.junction_table} (${rel.to_table.slice(0, -1)}_id);`);
      }
    }

    // Updated_at trigger
    if (model.fields.some(f => f.name === "updated_at")) {
      lines.push(``);
      lines.push(`CREATE OR REPLACE FUNCTION update_${tableName}_updated_at()`);
      lines.push(`RETURNS TRIGGER AS $$`);
      lines.push(`BEGIN`);
      lines.push(`  NEW.updated_at = NOW();`);
      lines.push(`  RETURN NEW;`);
      lines.push(`END;`);
      lines.push(`$$ LANGUAGE plpgsql;`);
      lines.push(``);
      lines.push(`CREATE TRIGGER trg_${tableName}_updated_at`);
      lines.push(`  BEFORE UPDATE ON ${tableName}`);
      lines.push(`  FOR EACH ROW`);
      lines.push(`  EXECUTE FUNCTION update_${tableName}_updated_at();`);
    }

    lines.push(``);

    return {
      path: `schema/${toSnakeCase(model.name)}.sql`,
      content: lines.join("\n"),
      language: "sql",
      source_module: mod.id,
    };
  }

  // â”€â”€â”€ Shared Types â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  private emitSharedTypes(system: IR.IRSystem): EmittedFile {
    const lines: string[] = [];
    lines.push(`// Generated by BoneScript compiler. DO NOT EDIT.`);
    lines.push(`// Source: ${system.source_hash}`);
    lines.push(``);

    for (const mod of system.modules) {
      for (const model of mod.models) {
        lines.push(`export interface ${model.name} {`);
        for (const field of model.fields) {
          const nullable = field.nullable ? " | null" : "";
          lines.push(`  ${field.name}: ${toTsType(field.type)}${nullable};`);
        }
        lines.push(`}`);
        lines.push(``);
      }
    }

    // Common types
    lines.push(`export interface ServiceError {`);
    lines.push(`  code: string;`);
    lines.push(`  message: string;`);
    lines.push(`  details?: unknown;`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export type Result<T, E = ServiceError> =`);
    lines.push(`  | { ok: true; value: T }`);
    lines.push(`  | { ok: false; error: E };`);
    lines.push(``);
    lines.push(`export interface RequestContext {`);
    lines.push(`  authenticated: boolean;`);
    lines.push(`  actor_id: string | null;`);
    lines.push(`  trace_id: string;`);
    lines.push(`  correlation_id: string;`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export interface PaginatedResult<T> {`);
    lines.push(`  items: T[];`);
    lines.push(`  total: number;`);
    lines.push(`  page: number;`);
    lines.push(`  page_size: number;`);
    lines.push(`}`);
    lines.push(``);

    return {
      path: `types/models.ts`,
      content: lines.join("\n"),
      language: "typescript",
      source_module: "shared",
    };
  }

  // â”€â”€â”€ Event Types â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  private emitEventTypes(system: IR.IRSystem): EmittedFile {
    const lines: string[] = [];
    lines.push(`// Generated by BoneScript compiler. DO NOT EDIT.`);
    lines.push(`// Source: ${system.source_hash}`);
    lines.push(``);

    for (const ev of system.events) {
      lines.push(`export interface ${ev.name}Event {`);
      lines.push(`  type: "${ev.name}";`);
      lines.push(`  payload: {`);
      for (const field of ev.payload) {
        const nullable = field.nullable ? " | null" : "";
        lines.push(`    ${field.name}: ${toTsType(field.type)}${nullable};`);
      }
      lines.push(`  };`);
      lines.push(`  metadata: {`);
      lines.push(`    source: string;`);
      lines.push(`    timestamp: Date;`);
      lines.push(`    correlation_id: string;`);
      lines.push(`    causation_id: string;`);
      lines.push(`  };`);
      lines.push(`}`);
      lines.push(``);
    }

    // Union type of all events
    const eventNames = system.events.map(e => `${e.name}Event`);
    lines.push(`export type SystemEvent = ${eventNames.join(" | ")};`);
    lines.push(``);

    // Event bus interface
    lines.push(`export interface EventBus {`);
    lines.push(`  publish(event: SystemEvent): Promise<void>;`);
    lines.push(`  subscribe(type: string, handler: (event: SystemEvent) => Promise<void>): void;`);
    lines.push(`}`);
    lines.push(``);

    return {
      path: `types/events.ts`,
      content: lines.join("\n"),
      language: "typescript",
      source_module: "shared",
    };
  }

  // â”€â”€â”€ Service Implementation â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  private emitService(mod: IR.IRModule, system: IR.IRSystem): EmittedFile {
    const lines: string[] = [];
    lines.push(`// Generated by BoneScript compiler. DO NOT EDIT.`);
    lines.push(`// Source: ${system.source_hash}`);
    lines.push(`// Module: ${mod.name} (${mod.kind})`);
    lines.push(``);
    lines.push(`import { Result, RequestContext, ServiceError, PaginatedResult } from "../types/models";`);
    lines.push(``);

    for (const iface of mod.interfaces) {
      // Interface definition
      lines.push(`export interface ${iface.name} {`);
      for (const method of iface.methods) {
        const params = method.input.map(f => `${f.name}: ${toTsType(f.type)}`).join(", ");
        const ctxParam = method.authenticated ? "ctx: RequestContext" : "";
        const allParams = [ctxParam, params].filter(Boolean).join(", ");
        lines.push(`  ${method.name}(${allParams}): Promise<Result<${toTsType(method.output)}>>;`);
      }
      lines.push(`}`);
      lines.push(``);

      // Implementation class
      lines.push(`export class ${mod.name} implements ${iface.name} {`);
      for (const method of iface.methods) {
        lines.push(this.emitMethod(method, mod, system));
      }
      lines.push(`}`);
      lines.push(``);
    }

    return {
      path: `services/${toSnakeCase(mod.name)}.ts`,
      content: lines.join("\n"),
      language: "typescript",
      source_module: mod.id,
    };
  }

  private emitMethod(method: IR.IRMethod, mod: IR.IRModule, system: IR.IRSystem): string {
    const lines: string[] = [];
    const params = method.input.map(f => `${f.name}: ${toTsType(f.type)}`).join(", ");
    const ctxParam = method.authenticated ? "ctx: RequestContext" : "";
    const allParams = [ctxParam, params].filter(Boolean).join(", ");

    lines.push(`  async ${method.name}(${allParams}): Promise<Result<${toTsType(method.output)}>> {`);

    // Auth check
    if (method.authenticated) {
      lines.push(`    // [Guard] Authentication required`);
      lines.push(`    if (!ctx.authenticated) {`);
      lines.push(`      return { ok: false, error: { code: "UNAUTHORIZED", message: "Authentication required" } };`);
      lines.push(`    }`);
      lines.push(``);
    }

    // Preconditions
    if (method.preconditions.length > 0) {
      lines.push(`    // [Preconditions]`);
      for (const pre of method.preconditions) {
        lines.push(`    // CHECK: ${pre.description}`);
      }
      lines.push(``);
    }

    // Effects
    if (method.effects.length > 0) {
      lines.push(`    // [Effects] Applied in declaration order (deterministic)`);
      for (const eff of method.effects) {
        const opSymbol = eff.op === "assign" ? "=" : eff.op === "add" ? "+=" : "-=";
        lines.push(`    // EFFECT: ${eff.target} ${opSymbol} ${eff.value}`);
      }
      lines.push(``);
    }

    // Emissions
    if (method.emissions.length > 0) {
      lines.push(`    // [Events]`);
      for (const ev of method.emissions) {
        lines.push(`    // EMIT: ${ev}`);
      }
      lines.push(``);
    }

    // Real implementation — delegate to emitCapabilityBody for capabilities,
    // or generate CRUD SQL for standard methods

    if (method.pipeline) {
      lines.push(emitPipelineBody(method, "    "));
    } else if (method.algorithm) {
      lines.push(emitAlgorithmBody(method, "    "));
    } else if (method.effects.length > 0 || method.preconditions.length > 0) {
      // Capability with effects/preconditions — use the full capability body emitter
      try {
        lines.push(emitCapabilityBody(method, mod, system, "    "));
      } catch (err: unknown) {
        // Body generation failed — emit a visible compile-time warning in the generated
        // file so the developer knows this method needs attention, rather than silently
        // producing a broken stub.
        const msg = err instanceof Error ? err.message : String(err);
        lines.push(`    // ⚠ COMPILER WARNING: emitCapabilityBody failed for '${method.name}': ${msg.replace(/`/g, "'")}`);
        lines.push(`    // Effects: ${method.effects.map((e: any) => e.target + " " + e.op + " " + e.value).join("; ")}`);
        lines.push(`    return { ok: false, error: { code: "CODEGEN_FAILED", message: "Body generation failed for '${method.name}': " + ${JSON.stringify(msg)} } };`);
      }
    } else {
      // CRUD or simple method — emit a typed not-implemented stub
      lines.push(`    return { ok: false, error: { code: "NOT_IMPLEMENTED", message: "${method.name} not yet implemented" } };`);
    }
    lines.push(`  }`);
    lines.push(``);

    return lines.join("\n");
  }

  // â”€â”€â”€ State Machine â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  private emitStateMachine(sm: IR.IRStateMachine, mod: IR.IRModule, system: IR.IRSystem): EmittedFile {
    const lines: string[] = [];
    lines.push(`// Generated by BoneScript compiler. DO NOT EDIT.`);
    lines.push(`// Source: ${system.source_hash}`);
    lines.push(`// Entity: ${sm.entity}`);
    lines.push(``);

    // State type
    const stateUnion = sm.states.map(s => `"${s}"`).join(" | ");
    lines.push(`export type ${sm.entity}State = ${stateUnion};`);
    lines.push(``);

    // Transition table
    lines.push(`export const ${sm.entity.toUpperCase()}_TRANSITIONS: Record<${sm.entity}State, Record<string, ${sm.entity}State>> = {`);
    for (const state of sm.states) {
      const transitions = sm.transitions.filter(t => t.from === state);
      const entries = transitions.map(t => `"${t.trigger}": "${t.to}"`).join(", ");
      lines.push(`  "${state}": { ${entries} },`);
    }
    lines.push(`};`);
    lines.push(``);

    // Transition function
    lines.push(`export interface TransitionError {`);
    lines.push(`  current: ${sm.entity}State;`);
    lines.push(`  trigger: string;`);
    lines.push(`  message: string;`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export function transition${sm.entity}(`);
    lines.push(`  current: ${sm.entity}State,`);
    lines.push(`  trigger: string`);
    lines.push(`): { ok: true; state: ${sm.entity}State } | { ok: false; error: TransitionError } {`);
    lines.push(`  const next = ${sm.entity.toUpperCase()}_TRANSITIONS[current]?.[trigger];`);
    lines.push(`  if (!next) {`);
    lines.push(`    return {`);
    lines.push(`      ok: false,`);
    lines.push(`      error: {`);
    lines.push(`        current,`);
    lines.push(`        trigger,`);
    lines.push(`        message: \`Invalid transition: \${current} --[\${trigger}]--> ?\``);
    lines.push(`      }`);
    lines.push(`    };`);
    lines.push(`  }`);
    lines.push(`  return { ok: true, state: next };`);
    lines.push(`}`);
    lines.push(``);

    // Initial state
    lines.push(`export const ${sm.entity.toUpperCase()}_INITIAL: ${sm.entity}State = "${sm.initial}";`);
    lines.push(``);

    return {
      path: `services/state_machines/${toSnakeCase(sm.entity)}_states.ts`,
      content: lines.join("\n"),
      language: "typescript",
      source_module: mod.id,
    };
  }

  // â”€â”€â”€ Service Config (YAML) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  private emitServiceConfig(system: IR.IRSystem): EmittedFile {
    const lines: string[] = [];
    lines.push(`# Generated by BoneScript compiler. DO NOT EDIT.`);
    lines.push(`# Source: ${system.source_hash}`);
    lines.push(``);
    lines.push(`system:`);
    lines.push(`  name: ${system.name}`);
    lines.push(`  version: ${system.version}`);
    lines.push(`  domain: ${system.domain || "generic"}`);
    lines.push(``);
    lines.push(`services:`);

    for (const mod of system.modules) {
      if (mod.kind === "api_service" || mod.kind === "realtime_service") {
        lines.push(`  - name: ${toSnakeCase(mod.name)}`);
        lines.push(`    kind: ${mod.kind}`);
        lines.push(`    dependencies:`);
        for (const dep of mod.dependencies) {
          const depMod = system.modules.find(m => m.id === dep);
          if (depMod) lines.push(`      - ${toSnakeCase(depMod.name)}`);
        }
        for (const [key, val] of Object.entries(mod.config)) {
          lines.push(`    ${key}: ${val}`);
        }
        lines.push(``);
      }
    }

    return {
      path: `config/services.yaml`,
      content: lines.join("\n"),
      language: "yaml",
      source_module: "config",
    };
  }

  // â”€â”€â”€ Infrastructure Config (YAML) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  private emitInfraConfig(system: IR.IRSystem): EmittedFile {
    const lines: string[] = [];
    lines.push(`# Generated by BoneScript compiler. DO NOT EDIT.`);
    lines.push(`# Source: ${system.source_hash}`);
    lines.push(``);
    lines.push(`infrastructure:`);

    // Data stores
    lines.push(`  datastores:`);
    for (const mod of system.modules) {
      if (mod.kind === "data_store") {
        lines.push(`    - name: ${toSnakeCase(mod.name)}`);
        lines.push(`      engine: ${mod.config["engine"] || "postgresql"}`);
        lines.push(`      replicas: ${mod.config["replicas"] || 1}`);
        if (mod.config["retention_ms"]) lines.push(`      retention_ms: ${mod.config["retention_ms"]}`);
        if (mod.config["partition_key"]) lines.push(`      partition_key: ${mod.config["partition_key"]}`);
        lines.push(``);
      }
    }

    // Gateway
    lines.push(`  gateway:`);
    const gw = system.modules.find(m => m.kind === "gateway");
    if (gw) {
      for (const [key, val] of Object.entries(gw.config)) {
        lines.push(`    ${key}: ${val}`);
      }
    }
    lines.push(``);

    // Events
    if (system.events.length > 0) {
      lines.push(`  events:`);
      for (const ev of system.events) {
        lines.push(`    - name: ${ev.name}`);
        lines.push(`      delivery: ${ev.delivery}`);
        lines.push(`      ordering: ${ev.ordering}`);
        if (ev.ttl_ms) lines.push(`      ttl_ms: ${ev.ttl_ms}`);
        lines.push(``);
      }
    }

    return {
      path: `config/infrastructure.yaml`,
      content: lines.join("\n"),
      language: "yaml",
      source_module: "config",
    };
  }
}
