"""Patches emit_runtime.ts to use lazy pool and dotenv."""
import os, re

path = os.path.join(os.path.dirname(__file__), 'emit_runtime.ts')
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# Find and replace the emitDbClient function
# We'll find it by its start and replace up to the closing backtick
start_marker = 'export function emitDbClient(system: IR.IRSystem): string {'
end_marker = "\nexport function emitEventBus"

start_idx = content.find(start_marker)
end_idx = content.find(end_marker, start_idx)

if start_idx == -1 or end_idx == -1:
    print(f"Could not find markers. start={start_idx}, end={end_idx}")
    exit(1)

new_fn = '''export function emitDbClient(system: IR.IRSystem): string {
  const name = toSnakeCase(system.name);
  return [
    "// Generated by BoneScript compiler. DO NOT EDIT.",
    "import { Pool, PoolClient } from \\"pg\\";",
    "",
    "// Lazy pool — created on first use so DATABASE_URL is read after dotenv loads",
    "let _pool: Pool | null = null;",
    "function getPool(): Pool {",
    "  if (!_pool) {",
    `  _pool = new Pool({ connectionString: process.env.DATABASE_URL || "postgresql://localhost:5432/${name}", max: 20 });`,
    "  _pool.on(\\"error\\", (err: Error) => console.error(\\"[DB] Pool error (non-fatal):\\", err.message));",
    "  }",
    "  return _pool;",
    "}",
    "export const pool = new Proxy({} as Pool, { get(_t: any, p: any) { return (getPool() as any)[p]; } });",
    "",
    "export async function query<T = any>(text: string, params?: any[]): Promise<T[]> {",
    "  try { const result = await pool.query(text, params); return result.rows as T[]; }",
    "  catch (e: any) { throw new Error(`DB query failed: ${e.message}`); }",
    "}",
    "export async function queryOne<T = any>(text: string, params?: any[]): Promise<T | null> {",
    "  try { const rows = await query<T>(text, params); return rows[0] || null; }",
    "  catch (e: any) { throw new Error(`DB query failed: ${e.message}`); }",
    "}",
    "export async function execute(text: string, params?: any[]): Promise<number> {",
    "  try { const result = await pool.query(text, params); return result.rowCount || 0; }",
    "  catch (e: any) { throw new Error(`DB execute failed: ${e.message}`); }",
    "}",
    "export async function transaction<T>(fn: (client: PoolClient) => Promise<T>): Promise<T> {",
    "  const client = await pool.connect();",
    "  try { await client.query(\\"BEGIN\\"); const result = await fn(client); await client.query(\\"COMMIT\\"); return result; }",
    "  catch (e) { await client.query(\\"ROLLBACK\\"); throw e; }",
    "  finally { client.release(); }",
    "}",
  ].join("\\n");
}

'''

content = content[:start_idx] + new_fn + content[end_idx:]
with open(path, 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)
print(f"Done. File size: {os.path.getsize(path)}")
