-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: 85dbdc0221e5bebe
-- Module: ItemStore

CREATE TABLE IF NOT EXISTS item_stores (
  id UUID NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  quantity BIGINT NOT NULL,
  rarity VARCHAR NOT NULL,
  tradeable BOOLEAN NOT NULL,
  owner_id UUID NOT NULL,
  state VARCHAR NOT NULL,
  metadata JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);


CREATE OR REPLACE FUNCTION update_item_stores_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_item_stores_updated_at
  BEFORE UPDATE ON item_stores
  FOR EACH ROW
  EXECUTE FUNCTION update_item_stores_updated_at();
