-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: 85dbdc0221e5bebe
-- Module: PlayerStore

CREATE TABLE IF NOT EXISTS player_stores (
  id UUID NOT NULL PRIMARY KEY,
  username VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  password_hash VARCHAR NOT NULL,
  score BIGINT NOT NULL,
  level BIGINT NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);


CREATE OR REPLACE FUNCTION update_player_stores_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_player_stores_updated_at
  BEFORE UPDATE ON player_stores
  FOR EACH ROW
  EXECUTE FUNCTION update_player_stores_updated_at();
