-- Generated by BoneScript compiler. DO NOT EDIT.
-- Source: 85dbdc0221e5bebe
-- Module: TradeOfferService

CREATE TABLE IF NOT EXISTS trade_offers (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  from_player UUID NOT NULL,
  to_player UUID NOT NULL,
  offered_items JSONB NOT NULL,
  requested_items JSONB NOT NULL,
  status VARCHAR NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_trade_offers_from_player_to_player_status ON trade_offers (from_player, to_player, status);

CREATE OR REPLACE FUNCTION update_trade_offers_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_trade_offers_updated_at
  BEFORE UPDATE ON trade_offers
  FOR EACH ROW
  EXECUTE FUNCTION update_trade_offers_updated_at();
